/*
 * XCAN MH (Message Handler) Register Definitions
 *
 * Merged from xcand_mh_creg_MH_MAP_memoryMap.h and xcand_mh_regdef.h
 * Originally auto-generated by RegMan from IP-XACT description.
 * Adapted for AUTOSAR driver: platform-specific constructs removed.
 *
 * Contains:
 *   - MH register offset defines and bit-field union types (from memory map)
 *   - TX/RX descriptor structs and word unions (from regdef)
 *   - RX filter element union (from regdef)
 *
 * Source: xcan_sw_example (Robert Bosch GmbH)
 * Original RegMan version: v2009_009h2, Created: 10.08.2022
 */

#ifndef XCAN_MH_REGDEF_H
#define XCAN_MH_REGDEF_H

#include "xcan_platform.h"


/*-----------------------------------------------------------------------------
 * constants: MemoryMap MH_MAP of Component xcand_mh_creg
 *---------------------------------------------------------------------------*/
#define MH_MAP_LAST_ADDR 0x8fc
#define MH_MAP_ADDR_SPACE 0x900
#define MH_MAP_ADDR_SPACE_ALIGNED 0x1000
#define MH_MAP_DATA_WIDTH 32
#define MH_MAP_ADDR_UNIT_BITS 8
#define MH_MAP_ADDR_STEP 4

/*-----------------------------------------------------------------------------
* constants: absolute addresses of address Blocks
*---------------------------------------------------------------------------*/

#define XCAND_MH_CREG_BASE_ADDR 0x000UL
#define XCAND_MH_CREG_LENGTH 0x900UL
#define XCAND_MH_CREG_LAST_ADDR 0x8FFUL

/*-----------------------------------------------------------------------------
* constants: absolute addresses of address Blocks
*---------------------------------------------------------------------------*/
#define XCAND_MH_CREG_VERSION                    0x000
#define XCAND_MH_CREG_MH_CTRL                    0x004
#define XCAND_MH_CREG_MH_CFG                     0x008
#define XCAND_MH_CREG_MH_STS                     0x00C
#define XCAND_MH_CREG_MH_SFTY_CFG                0x010
#define XCAND_MH_CREG_MH_SFTY_CTRL               0x014
#define XCAND_MH_CREG_RX_FILTER_MEM_ADD          0x018
#define XCAND_MH_CREG_TX_DESC_MEM_ADD            0x01C
#define XCAND_MH_CREG_AXI_ADD_EXT                0x020
#define XCAND_MH_CREG_AXI_PARAMS                 0x024
#define XCAND_MH_CREG_MH_LOCK                    0x028
#define XCAND_MH_CREG_TX_DESC_ADD_PT             0x100
#define XCAND_MH_CREG_TX_STATISTICS              0x104
#define XCAND_MH_CREG_TX_FQ_STS0                 0x108
#define XCAND_MH_CREG_TX_FQ_STS1                 0x10C
#define XCAND_MH_CREG_TX_FQ_CTRL0                0x110
#define XCAND_MH_CREG_TX_FQ_CTRL1                0x114
#define XCAND_MH_CREG_TX_FQ_CTRL2                0x118
#define XCAND_MH_CREG_TX_FQ_ADD_PT0              0x120
#define XCAND_MH_CREG_TX_FQ_START_ADD0           0x124
#define XCAND_MH_CREG_TX_FQ_SIZE0                0x128
#define XCAND_MH_CREG_TX_FQ_ADD_PT1              0x130
#define XCAND_MH_CREG_TX_FQ_START_ADD1           0x134
#define XCAND_MH_CREG_TX_FQ_SIZE1                0x138
#define XCAND_MH_CREG_TX_FQ_ADD_PT2              0x140
#define XCAND_MH_CREG_TX_FQ_START_ADD2           0x144
#define XCAND_MH_CREG_TX_FQ_SIZE2                0x148
#define XCAND_MH_CREG_TX_FQ_ADD_PT3              0x150
#define XCAND_MH_CREG_TX_FQ_START_ADD3           0x154
#define XCAND_MH_CREG_TX_FQ_SIZE3                0x158
#define XCAND_MH_CREG_TX_FQ_ADD_PT4              0x160
#define XCAND_MH_CREG_TX_FQ_START_ADD4           0x164
#define XCAND_MH_CREG_TX_FQ_SIZE4                0x168
#define XCAND_MH_CREG_TX_FQ_ADD_PT5              0x170
#define XCAND_MH_CREG_TX_FQ_START_ADD5           0x174
#define XCAND_MH_CREG_TX_FQ_SIZE5                0x178
#define XCAND_MH_CREG_TX_FQ_ADD_PT6              0x180
#define XCAND_MH_CREG_TX_FQ_START_ADD6           0x184
#define XCAND_MH_CREG_TX_FQ_SIZE6                0x188
#define XCAND_MH_CREG_TX_FQ_ADD_PT7              0x190
#define XCAND_MH_CREG_TX_FQ_START_ADD7           0x194
#define XCAND_MH_CREG_TX_FQ_SIZE7                0x198
#define XCAND_MH_CREG_TX_PQ_STS0                 0x300
#define XCAND_MH_CREG_TX_PQ_STS1                 0x304
#define XCAND_MH_CREG_TX_PQ_CTRL0                0x30C
#define XCAND_MH_CREG_TX_PQ_CTRL1                0x310
#define XCAND_MH_CREG_TX_PQ_CTRL2                0x314
#define XCAND_MH_CREG_TX_PQ_START_ADD            0x318
#define XCAND_MH_CREG_RX_DESC_ADD_PT             0x400
#define XCAND_MH_CREG_RX_STATISTICS              0x404
#define XCAND_MH_CREG_RX_FQ_STS0                 0x408
#define XCAND_MH_CREG_RX_FQ_STS1                 0x40C
#define XCAND_MH_CREG_RX_FQ_STS2                 0x410
#define XCAND_MH_CREG_RX_FQ_CTRL0                0x414
#define XCAND_MH_CREG_RX_FQ_CTRL1                0x418
#define XCAND_MH_CREG_RX_FQ_CTRL2                0x41C
#define XCAND_MH_CREG_RX_FQ_ADD_PT0              0x420
#define XCAND_MH_CREG_RX_FQ_START_ADD0           0x424
#define XCAND_MH_CREG_RX_FQ_SIZE0                0x428
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD0        0x42C
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT0           0x430
#define XCAND_MH_CREG_RX_FQ_ADD_PT1              0x438
#define XCAND_MH_CREG_RX_FQ_START_ADD1           0x43C
#define XCAND_MH_CREG_RX_FQ_SIZE1                0x440
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD1        0x444
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT1           0x448
#define XCAND_MH_CREG_RX_FQ_ADD_PT2              0x450
#define XCAND_MH_CREG_RX_FQ_START_ADD2           0x454
#define XCAND_MH_CREG_RX_FQ_SIZE2                0x458
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD2        0x45C
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT2           0x460
#define XCAND_MH_CREG_RX_FQ_ADD_PT3              0x468
#define XCAND_MH_CREG_RX_FQ_START_ADD3           0x46C
#define XCAND_MH_CREG_RX_FQ_SIZE3                0x470
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD3        0x474
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT3           0x478
#define XCAND_MH_CREG_RX_FQ_ADD_PT4              0x480
#define XCAND_MH_CREG_RX_FQ_START_ADD4           0x484
#define XCAND_MH_CREG_RX_FQ_SIZE4                0x488
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD4        0x48C
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT4           0x490
#define XCAND_MH_CREG_RX_FQ_ADD_PT5              0x498
#define XCAND_MH_CREG_RX_FQ_START_ADD5           0x49C
#define XCAND_MH_CREG_RX_FQ_SIZE5                0x4A0
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD5        0x4A4
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT5           0x4A8
#define XCAND_MH_CREG_RX_FQ_ADD_PT6              0x4B0
#define XCAND_MH_CREG_RX_FQ_START_ADD6           0x4B4
#define XCAND_MH_CREG_RX_FQ_SIZE6                0x4B8
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD6        0x4BC
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT6           0x4C0
#define XCAND_MH_CREG_RX_FQ_ADD_PT7              0x4C8
#define XCAND_MH_CREG_RX_FQ_START_ADD7           0x4CC
#define XCAND_MH_CREG_RX_FQ_SIZE7                0x4D0
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD7        0x4D4
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT7           0x4D8
#define XCAND_MH_CREG_TX_FILTER_CTRL0            0x600
#define XCAND_MH_CREG_TX_FILTER_CTRL1            0x604
#define XCAND_MH_CREG_TX_FILTER_REFVAL0          0x608
#define XCAND_MH_CREG_TX_FILTER_REFVAL1          0x60C
#define XCAND_MH_CREG_TX_FILTER_REFVAL2          0x610
#define XCAND_MH_CREG_TX_FILTER_REFVAL3          0x614
#define XCAND_MH_CREG_RX_FILTER_CTRL             0x680
#define XCAND_MH_CREG_TX_FQ_INT_STS              0x700
#define XCAND_MH_CREG_RX_FQ_INT_STS              0x704
#define XCAND_MH_CREG_TX_PQ_INT_STS0             0x708
#define XCAND_MH_CREG_TX_PQ_INT_STS1             0x70C
#define XCAND_MH_CREG_STATS_INT_STS              0x710
#define XCAND_MH_CREG_ERR_INT_STS                0x714
#define XCAND_MH_CREG_SFTY_INT_STS               0x718
#define XCAND_MH_CREG_AXI_ERR_INFO               0x71C
#define XCAND_MH_CREG_DESC_ERR_INFO0             0x720
#define XCAND_MH_CREG_DESC_ERR_INFO1             0x724
#define XCAND_MH_CREG_TX_FILTER_ERR_INFO         0x728
#define XCAND_MH_CREG_DEBUG_TEST_CTRL            0x800
#define XCAND_MH_CREG_INT_TEST0                  0x804
#define XCAND_MH_CREG_INT_TEST1                  0x808
#define XCAND_MH_CREG_TX_SCAN_FC                 0x810
#define XCAND_MH_CREG_TX_SCAN_BC                 0x814
#define XCAND_MH_CREG_TX_FQ_DESC_VALID           0x818
#define XCAND_MH_CREG_TX_PQ_DESC_VALID           0x81C
#define XCAND_MH_CREG_CRC_CTRL                   0x880
#define XCAND_MH_CREG_CRC_REG                    0x884


/*-----------------------------------------------------------------------------
 * Register bit-field union types
 *---------------------------------------------------------------------------*/


/*-----------------------------------------------------------------------------
 * Register specific bit fields
 *---------------------------------------------------------------------------*/

//Register: VERSION Addr: 0x000
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DayU8 : 8;
    uint32_t MonU8 : 8;
    uint32_t YearU4 : 4;
    uint32_t SubstepU4 : 4;
    uint32_t StepU4 : 4;
    uint32_t RelU4 : 4;
  } as_s;
} XcandmhcregVersionUt;

#define RESET_VAL_XCAND_MH_CREG_VERSION 0x05621103


#define XCAND_MH_CREG_VERSION_DAY_MASK 0xff
#define XCAND_MH_CREG_VERSION_DAY_SHIFT 0

#define XCAND_MH_CREG_VERSION_MON_MASK 0xff00
#define XCAND_MH_CREG_VERSION_MON_SHIFT 8

#define XCAND_MH_CREG_VERSION_YEAR_MASK 0xf0000
#define XCAND_MH_CREG_VERSION_YEAR_SHIFT 16

#define XCAND_MH_CREG_VERSION_SUBSTEP_MASK 0xf00000
#define XCAND_MH_CREG_VERSION_SUBSTEP_SHIFT 20

#define XCAND_MH_CREG_VERSION_STEP_MASK 0xf000000
#define XCAND_MH_CREG_VERSION_STEP_SHIFT 24

#define XCAND_MH_CREG_VERSION_REL_MASK 0xf0000000
#define XCAND_MH_CREG_VERSION_REL_SHIFT 28

//Register: MH_CTRL Addr: 0x004
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t StartU1 : 1;
    uint32_t reserved1_u31 : 31;
  } as_s;
} XcandmhcregMhctrlUt;

#define RESET_VAL_XCAND_MH_CREG_MH_CTRL 0x00000000


#define XCAND_MH_CREG_MH_CTRL_START_MASK 0x1
#define XCAND_MH_CREG_MH_CTRL_START_SHIFT 0

//Register: MH_CFG Addr: 0x008
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t RxcontdcU1 : 1;
    uint32_t reserved1_u7 : 7;
    uint32_t MaxretransU3 : 3;
    uint32_t reserved11_u5 : 5;
    uint32_t InstnumU3 : 3;
    uint32_t reserved19_u13 : 13;
  } as_s;
} XcandmhcregMhcfgUt;

#define RESET_VAL_XCAND_MH_CREG_MH_CFG 0x00000700


#define XCAND_MH_CREG_MH_CFG_RX_CONT_DC_MASK 0x1
#define XCAND_MH_CREG_MH_CFG_RX_CONT_DC_SHIFT 0

#define XCAND_MH_CREG_MH_CFG_MAX_RETRANS_MASK 0x700
#define XCAND_MH_CREG_MH_CFG_MAX_RETRANS_SHIFT 8

#define XCAND_MH_CREG_MH_CFG_INST_NUM_MASK 0x70000
#define XCAND_MH_CREG_MH_CFG_INST_NUM_SHIFT 16

//Register: MH_STS Addr: 0x00C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t BusyU1 : 1;
    uint32_t reserved1_u3 : 3;
    uint32_t EnableU1 : 1;
    uint32_t reserved5_u3 : 3;
    uint32_t ClockactiveU1 : 1;
    uint32_t reserved9_u23 : 23;
  } as_s;
} XcandmhcregMhstsUt;

#define RESET_VAL_XCAND_MH_CREG_MH_STS 0x00000100


#define XCAND_MH_CREG_MH_STS_BUSY_MASK 0x1
#define XCAND_MH_CREG_MH_STS_BUSY_SHIFT 0

#define XCAND_MH_CREG_MH_STS_ENABLE_MASK 0x10
#define XCAND_MH_CREG_MH_STS_ENABLE_SHIFT 4

#define XCAND_MH_CREG_MH_STS_CLOCK_ACTIVE_MASK 0x100
#define XCAND_MH_CREG_MH_STS_CLOCK_ACTIVE_SHIFT 8

//Register: MH_SFTY_CFG Addr: 0x010
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DmatovalU8 : 8;
    uint32_t MemtovalU8 : 8;
    uint32_t PrttovalU14 : 14;
    uint32_t PrescalerU2 : 2;
  } as_s;
} XcandmhcregMhsftycfgUt;

#define RESET_VAL_XCAND_MH_CREG_MH_SFTY_CFG 0x00000000


#define XCAND_MH_CREG_MH_SFTY_CFG_DMA_TO_VAL_MASK 0xff
#define XCAND_MH_CREG_MH_SFTY_CFG_DMA_TO_VAL_SHIFT 0

#define XCAND_MH_CREG_MH_SFTY_CFG_MEM_TO_VAL_MASK 0xff00
#define XCAND_MH_CREG_MH_SFTY_CFG_MEM_TO_VAL_SHIFT 8

#define XCAND_MH_CREG_MH_SFTY_CFG_PRT_TO_VAL_MASK 0x3fff0000
#define XCAND_MH_CREG_MH_SFTY_CFG_PRT_TO_VAL_SHIFT 16

#define XCAND_MH_CREG_MH_SFTY_CFG_PRESCALER_MASK 0xc0000000
#define XCAND_MH_CREG_MH_SFTY_CFG_PRESCALER_SHIFT 30

//Register: MH_SFTY_CTRL Addr: 0x014
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t TxdesccrcenU1 : 1;
    uint32_t RxdesccrcenU1 : 1;
    uint32_t MemprotenU1 : 1;
    uint32_t RxdpparityenU1 : 1;
    uint32_t TxdpparityenU1 : 1;
    uint32_t TxapparityenU1 : 1;
    uint32_t RxapparityenU1 : 1;
    uint32_t DmachchkenU1 : 1;
    uint32_t DmatoenU1 : 1;
    uint32_t MemtoenU1 : 1;
    uint32_t PrttoenU1 : 1;
    uint32_t reserved11_u21 : 21;
  } as_s;
} XcandmhcregMhsftyctrlUt;

#define RESET_VAL_XCAND_MH_CREG_MH_SFTY_CTRL 0x00000000


#define XCAND_MH_CREG_MH_SFTY_CTRL_TX_DESC_CRC_EN_MASK 0x1
#define XCAND_MH_CREG_MH_SFTY_CTRL_TX_DESC_CRC_EN_SHIFT 0

#define XCAND_MH_CREG_MH_SFTY_CTRL_RX_DESC_CRC_EN_MASK 0x2
#define XCAND_MH_CREG_MH_SFTY_CTRL_RX_DESC_CRC_EN_SHIFT 1

#define XCAND_MH_CREG_MH_SFTY_CTRL_MEM_PROT_EN_MASK 0x4
#define XCAND_MH_CREG_MH_SFTY_CTRL_MEM_PROT_EN_SHIFT 2

#define XCAND_MH_CREG_MH_SFTY_CTRL_RX_DP_PARITY_EN_MASK 0x8
#define XCAND_MH_CREG_MH_SFTY_CTRL_RX_DP_PARITY_EN_SHIFT 3

#define XCAND_MH_CREG_MH_SFTY_CTRL_TX_DP_PARITY_EN_MASK 0x10
#define XCAND_MH_CREG_MH_SFTY_CTRL_TX_DP_PARITY_EN_SHIFT 4

#define XCAND_MH_CREG_MH_SFTY_CTRL_TX_AP_PARITY_EN_MASK 0x20
#define XCAND_MH_CREG_MH_SFTY_CTRL_TX_AP_PARITY_EN_SHIFT 5

#define XCAND_MH_CREG_MH_SFTY_CTRL_RX_AP_PARITY_EN_MASK 0x40
#define XCAND_MH_CREG_MH_SFTY_CTRL_RX_AP_PARITY_EN_SHIFT 6

#define XCAND_MH_CREG_MH_SFTY_CTRL_DMA_CH_CHK_EN_MASK 0x80
#define XCAND_MH_CREG_MH_SFTY_CTRL_DMA_CH_CHK_EN_SHIFT 7

#define XCAND_MH_CREG_MH_SFTY_CTRL_DMA_TO_EN_MASK 0x100
#define XCAND_MH_CREG_MH_SFTY_CTRL_DMA_TO_EN_SHIFT 8

#define XCAND_MH_CREG_MH_SFTY_CTRL_MEM_TO_EN_MASK 0x200
#define XCAND_MH_CREG_MH_SFTY_CTRL_MEM_TO_EN_SHIFT 9

#define XCAND_MH_CREG_MH_SFTY_CTRL_PRT_TO_EN_MASK 0x400
#define XCAND_MH_CREG_MH_SFTY_CTRL_PRT_TO_EN_SHIFT 10

//Register: RX_FILTER_MEM_ADD Addr: 0x018
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t BaseaddrU16 : 16;
    uint32_t reserved16_u16 : 16;
  } as_s;
} XcandmhcregRxfiltermemaddUt;

#define RESET_VAL_XCAND_MH_CREG_RX_FILTER_MEM_ADD 0x00000000


#define XCAND_MH_CREG_RX_FILTER_MEM_ADD_BASE_ADDR_MASK 0xffff
#define XCAND_MH_CREG_RX_FILTER_MEM_ADD_BASE_ADDR_SHIFT 0

//Register: TX_DESC_MEM_ADD Addr: 0x01C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FqbaseaddrU16 : 16;
    uint32_t PqbaseaddrU16 : 16;
  } as_s;
} XcandmhcregTxdescmemaddUt;

#define RESET_VAL_XCAND_MH_CREG_TX_DESC_MEM_ADD 0x00000000


#define XCAND_MH_CREG_TX_DESC_MEM_ADD_FQ_BASE_ADDR_MASK 0xffff
#define XCAND_MH_CREG_TX_DESC_MEM_ADD_FQ_BASE_ADDR_SHIFT 0

#define XCAND_MH_CREG_TX_DESC_MEM_ADD_PQ_BASE_ADDR_MASK 0xffff0000
#define XCAND_MH_CREG_TX_DESC_MEM_ADD_PQ_BASE_ADDR_SHIFT 16

//Register: AXI_ADD_EXT Addr: 0x020
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregAxiaddextUt;

#define RESET_VAL_XCAND_MH_CREG_AXI_ADD_EXT 0x00000000


#define XCAND_MH_CREG_AXI_ADD_EXT_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_AXI_ADD_EXT_VAL_SHIFT 0

//Register: AXI_PARAMS Addr: 0x024
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ArmaxpendU2 : 2;
    uint32_t reserved2_u2 : 2;
    uint32_t AwmaxpendU2 : 2;
    uint32_t reserved6_u26 : 26;
  } as_s;
} XcandmhcregAxiparamsUt;

#define RESET_VAL_XCAND_MH_CREG_AXI_PARAMS 0x00000000


#define XCAND_MH_CREG_AXI_PARAMS_AR_MAX_PEND_MASK 0x3
#define XCAND_MH_CREG_AXI_PARAMS_AR_MAX_PEND_SHIFT 0

#define XCAND_MH_CREG_AXI_PARAMS_AW_MAX_PEND_MASK 0x30
#define XCAND_MH_CREG_AXI_PARAMS_AW_MAX_PEND_SHIFT 4

//Register: MH_LOCK Addr: 0x028
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t UlkU16 : 16;
    uint32_t TmkU16 : 16;
  } as_s;
} XcandmhcregMhlockUt;

#define RESET_VAL_XCAND_MH_CREG_MH_LOCK 0x00000000


#define XCAND_MH_CREG_MH_LOCK_ULK_MASK 0xffff
#define XCAND_MH_CREG_MH_LOCK_ULK_SHIFT 0

#define XCAND_MH_CREG_MH_LOCK_TMK_MASK 0xffff0000
#define XCAND_MH_CREG_MH_LOCK_TMK_SHIFT 16

//Register: TX_DESC_ADD_PT Addr: 0x100
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxdescaddptUt;

#define RESET_VAL_XCAND_MH_CREG_TX_DESC_ADD_PT 0x00000000


#define XCAND_MH_CREG_TX_DESC_ADD_PT_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_DESC_ADD_PT_VAL_SHIFT 0

//Register: TX_STATISTICS Addr: 0x104
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t SuccU12 : 12;
    uint32_t reserved12_u4 : 4;
    uint32_t UnsuccU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregTxstatisticsUt;

#define RESET_VAL_XCAND_MH_CREG_TX_STATISTICS 0x00000000


#define XCAND_MH_CREG_TX_STATISTICS_SUCC_MASK 0xfff
#define XCAND_MH_CREG_TX_STATISTICS_SUCC_SHIFT 0

#define XCAND_MH_CREG_TX_STATISTICS_UNSUCC_MASK 0xfff0000
#define XCAND_MH_CREG_TX_STATISTICS_UNSUCC_SHIFT 16

//Register: TX_FQ_STS0 Addr: 0x108
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t BusyU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t StopU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregTxfqsts0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_STS0 0x00000000


#define XCAND_MH_CREG_TX_FQ_STS0_BUSY_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_STS0_BUSY_SHIFT 0

#define XCAND_MH_CREG_TX_FQ_STS0_STOP_MASK 0xff0000
#define XCAND_MH_CREG_TX_FQ_STS0_STOP_SHIFT 16

//Register: TX_FQ_STS1 Addr: 0x10C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t UnvalidU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t ErrorU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregTxfqsts1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_STS1 0x00000000


#define XCAND_MH_CREG_TX_FQ_STS1_UNVALID_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_STS1_UNVALID_SHIFT 0

#define XCAND_MH_CREG_TX_FQ_STS1_ERROR_MASK 0xff0000
#define XCAND_MH_CREG_TX_FQ_STS1_ERROR_SHIFT 16

//Register: TX_FQ_CTRL0 Addr: 0x110
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t StartU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregTxfqctrl0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_CTRL0 0x00000000


#define XCAND_MH_CREG_TX_FQ_CTRL0_START_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_CTRL0_START_SHIFT 0

//Register: TX_FQ_CTRL1 Addr: 0x114
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t AbortU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregTxfqctrl1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_CTRL1 0x00000000


#define XCAND_MH_CREG_TX_FQ_CTRL1_ABORT_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_CTRL1_ABORT_SHIFT 0

//Register: TX_FQ_CTRL2 Addr: 0x118
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t EnableU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregTxfqctrl2Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_CTRL2 0x00000000


#define XCAND_MH_CREG_TX_FQ_CTRL2_ENABLE_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_CTRL2_ENABLE_SHIFT 0

//Register: TX_FQ_ADD_PT0 Addr: 0x120
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT0 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT0_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT0_VAL_SHIFT 0

//Register: TX_FQ_START_ADD0 Addr: 0x124
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD0 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD0_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD0_VAL_SHIFT 0

//Register: TX_FQ_SIZE0 Addr: 0x128
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE0 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE0_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE0_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT1 Addr: 0x130
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT1 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT1_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT1_VAL_SHIFT 0

//Register: TX_FQ_START_ADD1 Addr: 0x134
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD1 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD1_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD1_VAL_SHIFT 0

//Register: TX_FQ_SIZE1 Addr: 0x138
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE1 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE1_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE1_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT2 Addr: 0x140
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt2Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT2 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT2_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT2_VAL_SHIFT 0

//Register: TX_FQ_START_ADD2 Addr: 0x144
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd2Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD2 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD2_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD2_VAL_SHIFT 0

//Register: TX_FQ_SIZE2 Addr: 0x148
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize2Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE2 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE2_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE2_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT3 Addr: 0x150
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt3Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT3 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT3_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT3_VAL_SHIFT 0

//Register: TX_FQ_START_ADD3 Addr: 0x154
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd3Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD3 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD3_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD3_VAL_SHIFT 0

//Register: TX_FQ_SIZE3 Addr: 0x158
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize3Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE3 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE3_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE3_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT4 Addr: 0x160
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt4Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT4 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT4_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT4_VAL_SHIFT 0

//Register: TX_FQ_START_ADD4 Addr: 0x164
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd4Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD4 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD4_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD4_VAL_SHIFT 0

//Register: TX_FQ_SIZE4 Addr: 0x168
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize4Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE4 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE4_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE4_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT5 Addr: 0x170
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt5Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT5 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT5_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT5_VAL_SHIFT 0

//Register: TX_FQ_START_ADD5 Addr: 0x174
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd5Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD5 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD5_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD5_VAL_SHIFT 0

//Register: TX_FQ_SIZE5 Addr: 0x178
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize5Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE5 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE5_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE5_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT6 Addr: 0x180
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt6Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT6 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT6_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT6_VAL_SHIFT 0

//Register: TX_FQ_START_ADD6 Addr: 0x184
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd6Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD6 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD6_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD6_VAL_SHIFT 0

//Register: TX_FQ_SIZE6 Addr: 0x188
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize6Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE6 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE6_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE6_MAX_DESC_SHIFT 0

//Register: TX_FQ_ADD_PT7 Addr: 0x190
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqaddpt7Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_ADD_PT7 0x00000000


#define XCAND_MH_CREG_TX_FQ_ADD_PT7_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_ADD_PT7_VAL_SHIFT 0

//Register: TX_FQ_START_ADD7 Addr: 0x194
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxfqstartadd7Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_START_ADD7 0x00000000


#define XCAND_MH_CREG_TX_FQ_START_ADD7_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_FQ_START_ADD7_VAL_SHIFT 0

//Register: TX_FQ_SIZE7 Addr: 0x198
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u22 : 22;
  } as_s;
} XcandmhcregTxfqsize7Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_SIZE7 0x00000000


#define XCAND_MH_CREG_TX_FQ_SIZE7_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_TX_FQ_SIZE7_MAX_DESC_SHIFT 0

//Register: TX_PQ_STS0 Addr: 0x300
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t BusyU32 : 32;
  } as_s;
} XcandmhcregTxpqsts0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_STS0 0x00000000


#define XCAND_MH_CREG_TX_PQ_STS0_BUSY_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_STS0_BUSY_SHIFT 0

//Register: TX_PQ_STS1 Addr: 0x304
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t SentU32 : 32;
  } as_s;
} XcandmhcregTxpqsts1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_STS1 0x00000000


#define XCAND_MH_CREG_TX_PQ_STS1_SENT_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_STS1_SENT_SHIFT 0

//Register: TX_PQ_CTRL0 Addr: 0x30C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t StartU32 : 32;
  } as_s;
} XcandmhcregTxpqctrl0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_CTRL0 0x00000000


#define XCAND_MH_CREG_TX_PQ_CTRL0_START_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_CTRL0_START_SHIFT 0

//Register: TX_PQ_CTRL1 Addr: 0x310
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t AbortU32 : 32;
  } as_s;
} XcandmhcregTxpqctrl1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_CTRL1 0x00000000


#define XCAND_MH_CREG_TX_PQ_CTRL1_ABORT_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_CTRL1_ABORT_SHIFT 0

//Register: TX_PQ_CTRL2 Addr: 0x314
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t EnableU32 : 32;
  } as_s;
} XcandmhcregTxpqctrl2Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_CTRL2 0x00000000


#define XCAND_MH_CREG_TX_PQ_CTRL2_ENABLE_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_CTRL2_ENABLE_SHIFT 0

//Register: TX_PQ_START_ADD Addr: 0x318
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregTxpqstartaddUt;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_START_ADD 0x00000000


#define XCAND_MH_CREG_TX_PQ_START_ADD_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_START_ADD_VAL_SHIFT 0

//Register: RX_DESC_ADD_PT Addr: 0x400
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxdescaddptUt;

#define RESET_VAL_XCAND_MH_CREG_RX_DESC_ADD_PT 0x00000000


#define XCAND_MH_CREG_RX_DESC_ADD_PT_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_DESC_ADD_PT_VAL_SHIFT 0

//Register: RX_STATISTICS Addr: 0x404
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t SuccU12 : 12;
    uint32_t reserved12_u4 : 4;
    uint32_t UnsuccU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxstatisticsUt;

#define RESET_VAL_XCAND_MH_CREG_RX_STATISTICS 0x00000000


#define XCAND_MH_CREG_RX_STATISTICS_SUCC_MASK 0xfff
#define XCAND_MH_CREG_RX_STATISTICS_SUCC_SHIFT 0

#define XCAND_MH_CREG_RX_STATISTICS_UNSUCC_MASK 0xfff0000
#define XCAND_MH_CREG_RX_STATISTICS_UNSUCC_SHIFT 16

//Register: RX_FQ_STS0 Addr: 0x408
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t BusyU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t StopU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregRxfqsts0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_STS0 0x00000000


#define XCAND_MH_CREG_RX_FQ_STS0_BUSY_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_STS0_BUSY_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_STS0_STOP_MASK 0xff0000
#define XCAND_MH_CREG_RX_FQ_STS0_STOP_SHIFT 16

//Register: RX_FQ_STS1 Addr: 0x40C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t UnvalidU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t ErrorU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregRxfqsts1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_STS1 0x00000000


#define XCAND_MH_CREG_RX_FQ_STS1_UNVALID_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_STS1_UNVALID_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_STS1_ERROR_MASK 0xff0000
#define XCAND_MH_CREG_RX_FQ_STS1_ERROR_SHIFT 16

//Register: RX_FQ_STS2 Addr: 0x410
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DcfullU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregRxfqsts2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_STS2 0x00000000


#define XCAND_MH_CREG_RX_FQ_STS2_DC_FULL_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_STS2_DC_FULL_SHIFT 0

//Register: RX_FQ_CTRL0 Addr: 0x414
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t StartU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregRxfqctrl0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_CTRL0 0x00000000


#define XCAND_MH_CREG_RX_FQ_CTRL0_START_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_CTRL0_START_SHIFT 0

//Register: RX_FQ_CTRL1 Addr: 0x418
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t AbortU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregRxfqctrl1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_CTRL1 0x00000000


#define XCAND_MH_CREG_RX_FQ_CTRL1_ABORT_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_CTRL1_ABORT_SHIFT 0

//Register: RX_FQ_CTRL2 Addr: 0x41C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t EnableU8 : 8;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregRxfqctrl2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_CTRL2 0x00000000


#define XCAND_MH_CREG_RX_FQ_CTRL2_ENABLE_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_CTRL2_ENABLE_SHIFT 0

//Register: RX_FQ_ADD_PT0 Addr: 0x420
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT0 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT0_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT0_VAL_SHIFT 0

//Register: RX_FQ_START_ADD0 Addr: 0x424
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD0 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD0_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD0_VAL_SHIFT 0

//Register: RX_FQ_SIZE0 Addr: 0x428
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE0 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE0_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE0_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE0_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE0_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD0 Addr: 0x42C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD0 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD0_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD0_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT0 Addr: 0x430
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt0Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT0 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT0_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT0_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT1 Addr: 0x438
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT1 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT1_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT1_VAL_SHIFT 0

//Register: RX_FQ_START_ADD1 Addr: 0x43C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD1 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD1_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD1_VAL_SHIFT 0

//Register: RX_FQ_SIZE1 Addr: 0x440
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE1 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE1_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE1_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE1_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE1_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD1 Addr: 0x444
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD1 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD1_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD1_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT1 Addr: 0x448
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt1Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT1 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT1_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT1_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT2 Addr: 0x450
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT2 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT2_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT2_VAL_SHIFT 0

//Register: RX_FQ_START_ADD2 Addr: 0x454
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD2 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD2_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD2_VAL_SHIFT 0

//Register: RX_FQ_SIZE2 Addr: 0x458
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE2 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE2_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE2_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE2_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE2_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD2 Addr: 0x45C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD2 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD2_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD2_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT2 Addr: 0x460
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt2Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT2 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT2_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT2_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT3 Addr: 0x468
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt3Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT3 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT3_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT3_VAL_SHIFT 0

//Register: RX_FQ_START_ADD3 Addr: 0x46C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd3Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD3 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD3_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD3_VAL_SHIFT 0

//Register: RX_FQ_SIZE3 Addr: 0x470
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize3Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE3 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE3_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE3_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE3_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE3_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD3 Addr: 0x474
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd3Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD3 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD3_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD3_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT3 Addr: 0x478
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt3Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT3 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT3_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT3_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT4 Addr: 0x480
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt4Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT4 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT4_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT4_VAL_SHIFT 0

//Register: RX_FQ_START_ADD4 Addr: 0x484
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd4Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD4 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD4_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD4_VAL_SHIFT 0

//Register: RX_FQ_SIZE4 Addr: 0x488
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize4Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE4 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE4_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE4_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE4_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE4_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD4 Addr: 0x48C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd4Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD4 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD4_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD4_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT4 Addr: 0x490
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt4Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT4 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT4_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT4_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT5 Addr: 0x498
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt5Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT5 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT5_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT5_VAL_SHIFT 0

//Register: RX_FQ_START_ADD5 Addr: 0x49C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd5Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD5 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD5_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD5_VAL_SHIFT 0

//Register: RX_FQ_SIZE5 Addr: 0x4A0
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize5Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE5 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE5_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE5_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE5_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE5_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD5 Addr: 0x4A4
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd5Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD5 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD5_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD5_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT5 Addr: 0x4A8
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt5Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT5 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT5_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT5_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT6 Addr: 0x4B0
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt6Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT6 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT6_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT6_VAL_SHIFT 0

//Register: RX_FQ_START_ADD6 Addr: 0x4B4
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd6Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD6 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD6_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD6_VAL_SHIFT 0

//Register: RX_FQ_SIZE6 Addr: 0x4B8
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize6Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE6 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE6_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE6_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE6_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE6_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD6 Addr: 0x4BC
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd6Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD6 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD6_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD6_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT6 Addr: 0x4C0
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt6Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT6 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT6_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT6_VAL_SHIFT 0

//Register: RX_FQ_ADD_PT7 Addr: 0x4C8
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqaddpt7Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_ADD_PT7 0x00000000


#define XCAND_MH_CREG_RX_FQ_ADD_PT7_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_ADD_PT7_VAL_SHIFT 0

//Register: RX_FQ_START_ADD7 Addr: 0x4CC
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqstartadd7Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_START_ADD7 0x00000000


#define XCAND_MH_CREG_RX_FQ_START_ADD7_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_START_ADD7_VAL_SHIFT 0

//Register: RX_FQ_SIZE7 Addr: 0x4D0
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MaxdescU10 : 10;
    uint32_t reserved10_u6 : 6;
    uint32_t DcsizeU12 : 12;
    uint32_t reserved28_u4 : 4;
  } as_s;
} XcandmhcregRxfqsize7Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_SIZE7 0x00000000


#define XCAND_MH_CREG_RX_FQ_SIZE7_MAX_DESC_MASK 0x3ff
#define XCAND_MH_CREG_RX_FQ_SIZE7_MAX_DESC_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_SIZE7_DC_SIZE_MASK 0xfff0000
#define XCAND_MH_CREG_RX_FQ_SIZE7_DC_SIZE_SHIFT 16

//Register: RX_FQ_DC_START_ADD7 Addr: 0x4D4
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqdcstartadd7Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_DC_START_ADD7 0x00000000


#define XCAND_MH_CREG_RX_FQ_DC_START_ADD7_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_DC_START_ADD7_VAL_SHIFT 0

//Register: RX_FQ_RD_ADD_PT7 Addr: 0x4D8
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregRxfqrdaddpt7Ut;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_RD_ADD_PT7 0x00000000


#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT7_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_RX_FQ_RD_ADD_PT7_VAL_SHIFT 0

//Register: TX_FILTER_CTRL0 Addr: 0x600
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t CombU8 : 8;
    uint32_t MaskU8 : 8;
    uint32_t ModeU1 : 1;
    uint32_t CanfdU1 : 1;
    uint32_t CccanU1 : 1;
    uint32_t EnU1 : 1;
    uint32_t IrqenU1 : 1;
    uint32_t reserved21_u11 : 11;
  } as_s;
} XcandmhcregTxfilterctrl0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_CTRL0 0x00000000


#define XCAND_MH_CREG_TX_FILTER_CTRL0_COMB_MASK 0xff
#define XCAND_MH_CREG_TX_FILTER_CTRL0_COMB_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_CTRL0_MASK_MASK 0xff00
#define XCAND_MH_CREG_TX_FILTER_CTRL0_MASK_SHIFT 8

#define XCAND_MH_CREG_TX_FILTER_CTRL0_MODE_MASK 0x10000
#define XCAND_MH_CREG_TX_FILTER_CTRL0_MODE_SHIFT 16

#define XCAND_MH_CREG_TX_FILTER_CTRL0_CAN_FD_MASK 0x20000
#define XCAND_MH_CREG_TX_FILTER_CTRL0_CAN_FD_SHIFT 17

#define XCAND_MH_CREG_TX_FILTER_CTRL0_CC_CAN_MASK 0x40000
#define XCAND_MH_CREG_TX_FILTER_CTRL0_CC_CAN_SHIFT 18

#define XCAND_MH_CREG_TX_FILTER_CTRL0_EN_MASK 0x80000
#define XCAND_MH_CREG_TX_FILTER_CTRL0_EN_SHIFT 19

#define XCAND_MH_CREG_TX_FILTER_CTRL0_IRQ_EN_MASK 0x100000
#define XCAND_MH_CREG_TX_FILTER_CTRL0_IRQ_EN_SHIFT 20

//Register: TX_FILTER_CTRL1 Addr: 0x604
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValidU16 : 16;
    uint32_t FieldU16 : 16;
  } as_s;
} XcandmhcregTxfilterctrl1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_CTRL1 0x00000000


#define XCAND_MH_CREG_TX_FILTER_CTRL1_VALID_MASK 0xffff
#define XCAND_MH_CREG_TX_FILTER_CTRL1_VALID_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_CTRL1_FIELD_MASK 0xffff0000
#define XCAND_MH_CREG_TX_FILTER_CTRL1_FIELD_SHIFT 16

//Register: TX_FILTER_REFVAL0 Addr: 0x608
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Refval0U8 : 8;
    uint32_t Refval1U8 : 8;
    uint32_t Refval2U8 : 8;
    uint32_t Refval3U8 : 8;
  } as_s;
} XcandmhcregTxfilterrefval0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_REFVAL0 0x00000000


#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL0_MASK 0xff
#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL0_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL1_MASK 0xff00
#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL1_SHIFT 8

#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL2_MASK 0xff0000
#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL2_SHIFT 16

#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL3_MASK 0xff000000
#define XCAND_MH_CREG_TX_FILTER_REFVAL0_REF_VAL3_SHIFT 24

//Register: TX_FILTER_REFVAL1 Addr: 0x60C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Refval0U8 : 8;
    uint32_t Refval1U8 : 8;
    uint32_t Refval2U8 : 8;
    uint32_t Refval3U8 : 8;
  } as_s;
} XcandmhcregTxfilterrefval1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_REFVAL1 0x00000000


#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL0_MASK 0xff
#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL0_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL1_MASK 0xff00
#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL1_SHIFT 8

#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL2_MASK 0xff0000
#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL2_SHIFT 16

#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL3_MASK 0xff000000
#define XCAND_MH_CREG_TX_FILTER_REFVAL1_REF_VAL3_SHIFT 24

//Register: TX_FILTER_REFVAL2 Addr: 0x610
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Refval0U8 : 8;
    uint32_t Refval1U8 : 8;
    uint32_t Refval2U8 : 8;
    uint32_t Refval3U8 : 8;
  } as_s;
} XcandmhcregTxfilterrefval2Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_REFVAL2 0x00000000


#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL0_MASK 0xff
#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL0_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL1_MASK 0xff00
#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL1_SHIFT 8

#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL2_MASK 0xff0000
#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL2_SHIFT 16

#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL3_MASK 0xff000000
#define XCAND_MH_CREG_TX_FILTER_REFVAL2_REF_VAL3_SHIFT 24

//Register: TX_FILTER_REFVAL3 Addr: 0x614
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Refval0U8 : 8;
    uint32_t Refval1U8 : 8;
    uint32_t Refval2U8 : 8;
    uint32_t Refval3U8 : 8;
  } as_s;
} XcandmhcregTxfilterrefval3Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_REFVAL3 0x00000000


#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL0_MASK 0xff
#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL0_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL1_MASK 0xff00
#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL1_SHIFT 8

#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL2_MASK 0xff0000
#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL2_SHIFT 16

#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL3_MASK 0xff000000
#define XCAND_MH_CREG_TX_FILTER_REFVAL3_REF_VAL3_SHIFT 24

//Register: RX_FILTER_CTRL Addr: 0x680
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t NbfeU8 : 8;
    uint32_t ThresholdU5 : 5;
    uint32_t reserved13_u3 : 3;
    uint32_t AnmffqU3 : 3;
    uint32_t reserved19_u1 : 1;
    uint32_t AnmfU1 : 1;
    uint32_t AnffU1 : 1;
    uint32_t reserved22_u10 : 10;
  } as_s;
} XcandmhcregRxfilterctrlUt;

#define RESET_VAL_XCAND_MH_CREG_RX_FILTER_CTRL 0x00000000


#define XCAND_MH_CREG_RX_FILTER_CTRL_NB_FE_MASK 0xff
#define XCAND_MH_CREG_RX_FILTER_CTRL_NB_FE_SHIFT 0

#define XCAND_MH_CREG_RX_FILTER_CTRL_THRESHOLD_MASK 0x1f00
#define XCAND_MH_CREG_RX_FILTER_CTRL_THRESHOLD_SHIFT 8

#define XCAND_MH_CREG_RX_FILTER_CTRL_ANMF_FQ_MASK 0x70000
#define XCAND_MH_CREG_RX_FILTER_CTRL_ANMF_FQ_SHIFT 16

#define XCAND_MH_CREG_RX_FILTER_CTRL_ANMF_MASK 0x100000
#define XCAND_MH_CREG_RX_FILTER_CTRL_ANMF_SHIFT 20

#define XCAND_MH_CREG_RX_FILTER_CTRL_ANFF_MASK 0x200000
#define XCAND_MH_CREG_RX_FILTER_CTRL_ANFF_SHIFT 21

//Register: TX_FQ_INT_STS Addr: 0x700
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t SentU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t UnvalidU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregTxfqintstsUt;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_INT_STS 0x00000000


#define XCAND_MH_CREG_TX_FQ_INT_STS_SENT_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_INT_STS_SENT_SHIFT 0

#define XCAND_MH_CREG_TX_FQ_INT_STS_UNVALID_MASK 0xff0000
#define XCAND_MH_CREG_TX_FQ_INT_STS_UNVALID_SHIFT 16

//Register: RX_FQ_INT_STS Addr: 0x704
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ReceivedU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t UnvalidU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregRxfqintstsUt;

#define RESET_VAL_XCAND_MH_CREG_RX_FQ_INT_STS 0x00000000


#define XCAND_MH_CREG_RX_FQ_INT_STS_RECEIVED_MASK 0xff
#define XCAND_MH_CREG_RX_FQ_INT_STS_RECEIVED_SHIFT 0

#define XCAND_MH_CREG_RX_FQ_INT_STS_UNVALID_MASK 0xff0000
#define XCAND_MH_CREG_RX_FQ_INT_STS_UNVALID_SHIFT 16

//Register: TX_PQ_INT_STS0 Addr: 0x708
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t SentU32 : 32;
  } as_s;
} XcandmhcregTxpqintsts0Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_INT_STS0 0x00000000


#define XCAND_MH_CREG_TX_PQ_INT_STS0_SENT_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_INT_STS0_SENT_SHIFT 0

//Register: TX_PQ_INT_STS1 Addr: 0x70C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t UnvalidU32 : 32;
  } as_s;
} XcandmhcregTxpqintsts1Ut;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_INT_STS1 0x00000000


#define XCAND_MH_CREG_TX_PQ_INT_STS1_UNVALID_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_INT_STS1_UNVALID_SHIFT 0

//Register: STATS_INT_STS Addr: 0x710
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t TxsuccU1 : 1;
    uint32_t TxunsuccU1 : 1;
    uint32_t RxsuccU1 : 1;
    uint32_t RxunsuccU1 : 1;
    uint32_t reserved4_u28 : 28;
  } as_s;
} XcandmhcregStatsintstsUt;

#define RESET_VAL_XCAND_MH_CREG_STATS_INT_STS 0x00000000


#define XCAND_MH_CREG_STATS_INT_STS_TX_SUCC_MASK 0x1
#define XCAND_MH_CREG_STATS_INT_STS_TX_SUCC_SHIFT 0

#define XCAND_MH_CREG_STATS_INT_STS_TX_UNSUCC_MASK 0x2
#define XCAND_MH_CREG_STATS_INT_STS_TX_UNSUCC_SHIFT 1

#define XCAND_MH_CREG_STATS_INT_STS_RX_SUCC_MASK 0x4
#define XCAND_MH_CREG_STATS_INT_STS_RX_SUCC_SHIFT 2

#define XCAND_MH_CREG_STATS_INT_STS_RX_UNSUCC_MASK 0x8
#define XCAND_MH_CREG_STATS_INT_STS_RX_UNSUCC_SHIFT 3

//Register: ERR_INT_STS Addr: 0x714
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DptxackdoerrU1 : 1;
    uint32_t DprxfifodoerrU1 : 1;
    uint32_t DprxackdoerrU1 : 1;
    uint32_t DptxseqerrU1 : 1;
    uint32_t DprxseqerrU1 : 1;
    uint32_t reserved5_u27 : 27;
  } as_s;
} XcandmhcregErrintstsUt;

#define RESET_VAL_XCAND_MH_CREG_ERR_INT_STS 0x00000000


#define XCAND_MH_CREG_ERR_INT_STS_DP_TX_ACK_DO_ERR_MASK 0x1
#define XCAND_MH_CREG_ERR_INT_STS_DP_TX_ACK_DO_ERR_SHIFT 0

#define XCAND_MH_CREG_ERR_INT_STS_DP_RX_FIFO_DO_ERR_MASK 0x2
#define XCAND_MH_CREG_ERR_INT_STS_DP_RX_FIFO_DO_ERR_SHIFT 1

#define XCAND_MH_CREG_ERR_INT_STS_DP_RX_ACK_DO_ERR_MASK 0x4
#define XCAND_MH_CREG_ERR_INT_STS_DP_RX_ACK_DO_ERR_SHIFT 2

#define XCAND_MH_CREG_ERR_INT_STS_DP_TX_SEQ_ERR_MASK 0x8
#define XCAND_MH_CREG_ERR_INT_STS_DP_TX_SEQ_ERR_SHIFT 3

#define XCAND_MH_CREG_ERR_INT_STS_DP_RX_SEQ_ERR_MASK 0x10
#define XCAND_MH_CREG_ERR_INT_STS_DP_RX_SEQ_ERR_SHIFT 4

//Register: SFTY_INT_STS Addr: 0x718
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DmaaxiwrtoerrU1 : 1;
    uint32_t DmaaxirdtoerrU1 : 1;
    uint32_t DpprttxtoerrU1 : 1;
    uint32_t DpprtrxtoerrU1 : 1;
    uint32_t MemaxiwrtoerrU1 : 1;
    uint32_t MemaxirdtoerrU1 : 1;
    uint32_t DptxparityerrU1 : 1;
    uint32_t DprxparityerrU1 : 1;
    uint32_t AptxparityerrU1 : 1;
    uint32_t AprxparityerrU1 : 1;
    uint32_t TxdescreqerrU1 : 1;
    uint32_t TxdesccrcerrU1 : 1;
    uint32_t RxdescreqerrU1 : 1;
    uint32_t RxdesccrcerrU1 : 1;
    uint32_t MemsftyueU1 : 1;
    uint32_t MemsftyceU1 : 1;
    uint32_t AcktxparityerrU1 : 1;
    uint32_t AckrxparityerrU1 : 1;
    uint32_t reserved18_u14 : 14;
  } as_s;
} XcandmhcregSftyintstsUt;

#define RESET_VAL_XCAND_MH_CREG_SFTY_INT_STS 0x00000000


#define XCAND_MH_CREG_SFTY_INT_STS_DMA_AXI_WR_TO_ERR_MASK 0x1
#define XCAND_MH_CREG_SFTY_INT_STS_DMA_AXI_WR_TO_ERR_SHIFT 0

#define XCAND_MH_CREG_SFTY_INT_STS_DMA_AXI_RD_TO_ERR_MASK 0x2
#define XCAND_MH_CREG_SFTY_INT_STS_DMA_AXI_RD_TO_ERR_SHIFT 1

#define XCAND_MH_CREG_SFTY_INT_STS_DP_PRT_TX_TO_ERR_MASK 0x4
#define XCAND_MH_CREG_SFTY_INT_STS_DP_PRT_TX_TO_ERR_SHIFT 2

#define XCAND_MH_CREG_SFTY_INT_STS_DP_PRT_RX_TO_ERR_MASK 0x8
#define XCAND_MH_CREG_SFTY_INT_STS_DP_PRT_RX_TO_ERR_SHIFT 3

#define XCAND_MH_CREG_SFTY_INT_STS_MEM_AXI_WR_TO_ERR_MASK 0x10
#define XCAND_MH_CREG_SFTY_INT_STS_MEM_AXI_WR_TO_ERR_SHIFT 4

#define XCAND_MH_CREG_SFTY_INT_STS_MEM_AXI_RD_TO_ERR_MASK 0x20
#define XCAND_MH_CREG_SFTY_INT_STS_MEM_AXI_RD_TO_ERR_SHIFT 5

#define XCAND_MH_CREG_SFTY_INT_STS_DP_TX_PARITY_ERR_MASK 0x40
#define XCAND_MH_CREG_SFTY_INT_STS_DP_TX_PARITY_ERR_SHIFT 6

#define XCAND_MH_CREG_SFTY_INT_STS_DP_RX_PARITY_ERR_MASK 0x80
#define XCAND_MH_CREG_SFTY_INT_STS_DP_RX_PARITY_ERR_SHIFT 7

#define XCAND_MH_CREG_SFTY_INT_STS_AP_TX_PARITY_ERR_MASK 0x100
#define XCAND_MH_CREG_SFTY_INT_STS_AP_TX_PARITY_ERR_SHIFT 8

#define XCAND_MH_CREG_SFTY_INT_STS_AP_RX_PARITY_ERR_MASK 0x200
#define XCAND_MH_CREG_SFTY_INT_STS_AP_RX_PARITY_ERR_SHIFT 9

#define XCAND_MH_CREG_SFTY_INT_STS_TX_DESC_REQ_ERR_MASK 0x400
#define XCAND_MH_CREG_SFTY_INT_STS_TX_DESC_REQ_ERR_SHIFT 10

#define XCAND_MH_CREG_SFTY_INT_STS_TX_DESC_CRC_ERR_MASK 0x800
#define XCAND_MH_CREG_SFTY_INT_STS_TX_DESC_CRC_ERR_SHIFT 11

#define XCAND_MH_CREG_SFTY_INT_STS_RX_DESC_REQ_ERR_MASK 0x1000
#define XCAND_MH_CREG_SFTY_INT_STS_RX_DESC_REQ_ERR_SHIFT 12

#define XCAND_MH_CREG_SFTY_INT_STS_RX_DESC_CRC_ERR_MASK 0x2000
#define XCAND_MH_CREG_SFTY_INT_STS_RX_DESC_CRC_ERR_SHIFT 13

#define XCAND_MH_CREG_SFTY_INT_STS_MEM_SFTY_UE_MASK 0x4000
#define XCAND_MH_CREG_SFTY_INT_STS_MEM_SFTY_UE_SHIFT 14

#define XCAND_MH_CREG_SFTY_INT_STS_MEM_SFTY_CE_MASK 0x8000
#define XCAND_MH_CREG_SFTY_INT_STS_MEM_SFTY_CE_SHIFT 15

#define XCAND_MH_CREG_SFTY_INT_STS_ACK_TX_PARITY_ERR_MASK 0x10000
#define XCAND_MH_CREG_SFTY_INT_STS_ACK_TX_PARITY_ERR_SHIFT 16

#define XCAND_MH_CREG_SFTY_INT_STS_ACK_RX_PARITY_ERR_MASK 0x20000
#define XCAND_MH_CREG_SFTY_INT_STS_ACK_RX_PARITY_ERR_SHIFT 17

//Register: AXI_ERR_INFO Addr: 0x71C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DmaidU2 : 2;
    uint32_t DmarespU2 : 2;
    uint32_t MemidU2 : 2;
    uint32_t MemrespU2 : 2;
    uint32_t reserved8_u24 : 24;
  } as_s;
} XcandmhcregAxierrinfoUt;

#define RESET_VAL_XCAND_MH_CREG_AXI_ERR_INFO 0x00000000


#define XCAND_MH_CREG_AXI_ERR_INFO_DMA_ID_MASK 0x3
#define XCAND_MH_CREG_AXI_ERR_INFO_DMA_ID_SHIFT 0

#define XCAND_MH_CREG_AXI_ERR_INFO_DMA_RESP_MASK 0xc
#define XCAND_MH_CREG_AXI_ERR_INFO_DMA_RESP_SHIFT 2

#define XCAND_MH_CREG_AXI_ERR_INFO_MEM_ID_MASK 0x30
#define XCAND_MH_CREG_AXI_ERR_INFO_MEM_ID_SHIFT 4

#define XCAND_MH_CREG_AXI_ERR_INFO_MEM_RESP_MASK 0xc0
#define XCAND_MH_CREG_AXI_ERR_INFO_MEM_RESP_SHIFT 6

//Register: DESC_ERR_INFO0 Addr: 0x720
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t AddU32 : 32;
  } as_s;
} XcandmhcregDescerrinfo0Ut;

#define RESET_VAL_XCAND_MH_CREG_DESC_ERR_INFO0 0x00000000


#define XCAND_MH_CREG_DESC_ERR_INFO0_ADD_MASK 0xffffffff
#define XCAND_MH_CREG_DESC_ERR_INFO0_ADD_SHIFT 0

//Register: DESC_ERR_INFO1 Addr: 0x724
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FqnpqsnU5 : 5;
    uint32_t InU3 : 3;
    uint32_t PqU1 : 1;
    uint32_t RcU5 : 5;
    uint32_t reserved14_u1 : 1;
    uint32_t RxtxU1 : 1;
    uint32_t CrcU9 : 9;
    uint32_t reserved25_u7 : 7;
  } as_s;
} XcandmhcregDescerrinfo1Ut;

#define RESET_VAL_XCAND_MH_CREG_DESC_ERR_INFO1 0x00000000


#define XCAND_MH_CREG_DESC_ERR_INFO1_FQN_PQSN_MASK 0x1f
#define XCAND_MH_CREG_DESC_ERR_INFO1_FQN_PQSN_SHIFT 0

#define XCAND_MH_CREG_DESC_ERR_INFO1_IN_MASK 0xe0
#define XCAND_MH_CREG_DESC_ERR_INFO1_IN_SHIFT 5

#define XCAND_MH_CREG_DESC_ERR_INFO1_PQ_MASK 0x100
#define XCAND_MH_CREG_DESC_ERR_INFO1_PQ_SHIFT 8

#define XCAND_MH_CREG_DESC_ERR_INFO1_RC_MASK 0x3e00
#define XCAND_MH_CREG_DESC_ERR_INFO1_RC_SHIFT 9

#define XCAND_MH_CREG_DESC_ERR_INFO1_RX_TX_MASK 0x8000
#define XCAND_MH_CREG_DESC_ERR_INFO1_RX_TX_SHIFT 15

#define XCAND_MH_CREG_DESC_ERR_INFO1_CRC_MASK 0x1ff0000
#define XCAND_MH_CREG_DESC_ERR_INFO1_CRC_SHIFT 16

//Register: TX_FILTER_ERR_INFO Addr: 0x728
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FqU1 : 1;
    uint32_t FqnpqsU5 : 5;
    uint32_t reserved6_u26 : 26;
  } as_s;
} XcandmhcregTxfiltererrinfoUt;

#define RESET_VAL_XCAND_MH_CREG_TX_FILTER_ERR_INFO 0x00000000


#define XCAND_MH_CREG_TX_FILTER_ERR_INFO_FQ_MASK 0x1
#define XCAND_MH_CREG_TX_FILTER_ERR_INFO_FQ_SHIFT 0

#define XCAND_MH_CREG_TX_FILTER_ERR_INFO_FQN_PQS_MASK 0x3e
#define XCAND_MH_CREG_TX_FILTER_ERR_INFO_FQN_PQS_SHIFT 1

//Register: DEBUG_TEST_CTRL Addr: 0x800
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t TestirqenU1 : 1;
    uint32_t HdpenU1 : 1;
    uint32_t reserved2_u6 : 6;
    uint32_t HdpselU3 : 3;
    uint32_t reserved11_u21 : 21;
  } as_s;
} XcandmhcregDebugtestctrlUt;

#define RESET_VAL_XCAND_MH_CREG_DEBUG_TEST_CTRL 0x00000000


#define XCAND_MH_CREG_DEBUG_TEST_CTRL_TEST_IRQ_EN_MASK 0x1
#define XCAND_MH_CREG_DEBUG_TEST_CTRL_TEST_IRQ_EN_SHIFT 0

#define XCAND_MH_CREG_DEBUG_TEST_CTRL_HDP_EN_MASK 0x2
#define XCAND_MH_CREG_DEBUG_TEST_CTRL_HDP_EN_SHIFT 1

#define XCAND_MH_CREG_DEBUG_TEST_CTRL_HDP_SEL_MASK 0x700
#define XCAND_MH_CREG_DEBUG_TEST_CTRL_HDP_SEL_SHIFT 8

//Register: INT_TEST0 Addr: 0x804
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t TxfqirqU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t RxfqirqU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregInttest0Ut;

#define RESET_VAL_XCAND_MH_CREG_INT_TEST0 0x00000000


#define XCAND_MH_CREG_INT_TEST0_TX_FQ_IRQ_MASK 0xff
#define XCAND_MH_CREG_INT_TEST0_TX_FQ_IRQ_SHIFT 0

#define XCAND_MH_CREG_INT_TEST0_RX_FQ_IRQ_MASK 0xff0000
#define XCAND_MH_CREG_INT_TEST0_RX_FQ_IRQ_SHIFT 16

//Register: INT_TEST1 Addr: 0x808
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ResperrU2 : 2;
    uint32_t DmatoerrU1 : 1;
    uint32_t DmacherrU1 : 1;
    uint32_t DptoerrU1 : 1;
    uint32_t DpdoerrU1 : 1;
    uint32_t DpseqerrU1 : 1;
    uint32_t DpparityerrU1 : 1;
    uint32_t ApparityerrU1 : 1;
    uint32_t DescerrU1 : 1;
    uint32_t RegcrcerrU1 : 1;
    uint32_t MemsftyerrU1 : 1;
    uint32_t MemtoerrU1 : 1;
    uint32_t RxfiltererrU1 : 1;
    uint32_t RxabortirqU1 : 1;
    uint32_t TxabortirqU1 : 1;
    uint32_t TxfilterirqU1 : 1;
    uint32_t RxfilterirqU1 : 1;
    uint32_t StopirqU1 : 1;
    uint32_t StatsirqU1 : 1;
    uint32_t TxpqirqU1 : 1;
    uint32_t reserved21_u11 : 11;
  } as_s;
} XcandmhcregInttest1Ut;

#define RESET_VAL_XCAND_MH_CREG_INT_TEST1 0x00000000


#define XCAND_MH_CREG_INT_TEST1_RESP_ERR_MASK 0x3
#define XCAND_MH_CREG_INT_TEST1_RESP_ERR_SHIFT 0

#define XCAND_MH_CREG_INT_TEST1_DMA_TO_ERR_MASK 0x4
#define XCAND_MH_CREG_INT_TEST1_DMA_TO_ERR_SHIFT 2

#define XCAND_MH_CREG_INT_TEST1_DMA_CH_ERR_MASK 0x8
#define XCAND_MH_CREG_INT_TEST1_DMA_CH_ERR_SHIFT 3

#define XCAND_MH_CREG_INT_TEST1_DP_TO_ERR_MASK 0x10
#define XCAND_MH_CREG_INT_TEST1_DP_TO_ERR_SHIFT 4

#define XCAND_MH_CREG_INT_TEST1_DP_DO_ERR_MASK 0x20
#define XCAND_MH_CREG_INT_TEST1_DP_DO_ERR_SHIFT 5

#define XCAND_MH_CREG_INT_TEST1_DP_SEQ_ERR_MASK 0x40
#define XCAND_MH_CREG_INT_TEST1_DP_SEQ_ERR_SHIFT 6

#define XCAND_MH_CREG_INT_TEST1_DP_PARITY_ERR_MASK 0x80
#define XCAND_MH_CREG_INT_TEST1_DP_PARITY_ERR_SHIFT 7

#define XCAND_MH_CREG_INT_TEST1_AP_PARITY_ERR_MASK 0x100
#define XCAND_MH_CREG_INT_TEST1_AP_PARITY_ERR_SHIFT 8

#define XCAND_MH_CREG_INT_TEST1_DESC_ERR_MASK 0x200
#define XCAND_MH_CREG_INT_TEST1_DESC_ERR_SHIFT 9

#define XCAND_MH_CREG_INT_TEST1_REG_CRC_ERR_MASK 0x400
#define XCAND_MH_CREG_INT_TEST1_REG_CRC_ERR_SHIFT 10

#define XCAND_MH_CREG_INT_TEST1_MEM_SFTY_ERR_MASK 0x800
#define XCAND_MH_CREG_INT_TEST1_MEM_SFTY_ERR_SHIFT 11

#define XCAND_MH_CREG_INT_TEST1_MEM_TO_ERR_MASK 0x1000
#define XCAND_MH_CREG_INT_TEST1_MEM_TO_ERR_SHIFT 12

#define XCAND_MH_CREG_INT_TEST1_RX_FILTER_ERR_MASK 0x2000
#define XCAND_MH_CREG_INT_TEST1_RX_FILTER_ERR_SHIFT 13

#define XCAND_MH_CREG_INT_TEST1_RX_ABORT_IRQ_MASK 0x4000
#define XCAND_MH_CREG_INT_TEST1_RX_ABORT_IRQ_SHIFT 14

#define XCAND_MH_CREG_INT_TEST1_TX_ABORT_IRQ_MASK 0x8000
#define XCAND_MH_CREG_INT_TEST1_TX_ABORT_IRQ_SHIFT 15

#define XCAND_MH_CREG_INT_TEST1_TX_FILTER_IRQ_MASK 0x10000
#define XCAND_MH_CREG_INT_TEST1_TX_FILTER_IRQ_SHIFT 16

#define XCAND_MH_CREG_INT_TEST1_RX_FILTER_IRQ_MASK 0x20000
#define XCAND_MH_CREG_INT_TEST1_RX_FILTER_IRQ_SHIFT 17

#define XCAND_MH_CREG_INT_TEST1_STOP_IRQ_MASK 0x40000
#define XCAND_MH_CREG_INT_TEST1_STOP_IRQ_SHIFT 18

#define XCAND_MH_CREG_INT_TEST1_STATS_IRQ_MASK 0x80000
#define XCAND_MH_CREG_INT_TEST1_STATS_IRQ_SHIFT 19

#define XCAND_MH_CREG_INT_TEST1_TX_PQ_IRQ_MASK 0x100000
#define XCAND_MH_CREG_INT_TEST1_TX_PQ_IRQ_SHIFT 20

//Register: TX_SCAN_FC Addr: 0x810
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Fqpq0U1 : 1;
    uint32_t Fqnpqsn0U5 : 5;
    uint32_t reserved6_u2 : 2;
    uint32_t Fqpq1U1 : 1;
    uint32_t Fqnpqsn1U5 : 5;
    uint32_t reserved14_u2 : 2;
    uint32_t Fqpq2U1 : 1;
    uint32_t Fqnpqsn2U5 : 5;
    uint32_t reserved22_u2 : 2;
    uint32_t Fqpq3U1 : 1;
    uint32_t Fqnpqsn3U5 : 5;
    uint32_t reserved30_u2 : 2;
  } as_s;
} XcandmhcregTxscanfcUt;

#define RESET_VAL_XCAND_MH_CREG_TX_SCAN_FC 0x00000000


#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ0_MASK 0x1
#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ0_SHIFT 0

#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN0_MASK 0x3e
#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN0_SHIFT 1

#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ1_MASK 0x100
#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ1_SHIFT 8

#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN1_MASK 0x3e00
#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN1_SHIFT 9

#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ2_MASK 0x10000
#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ2_SHIFT 16

#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN2_MASK 0x3e0000
#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN2_SHIFT 17

#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ3_MASK 0x1000000
#define XCAND_MH_CREG_TX_SCAN_FC_FQ_PQ3_SHIFT 24

#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN3_MASK 0x3e000000
#define XCAND_MH_CREG_TX_SCAN_FC_FQN_PQSN3_SHIFT 25

//Register: TX_SCAN_BC Addr: 0x814
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FhpqU1 : 1;
    uint32_t FhfqnpqsnU5 : 5;
    uint32_t FhoffsetU10 : 10;
    uint32_t ShpqU1 : 1;
    uint32_t ShfqnpqsnU5 : 5;
    uint32_t ShoffsetU10 : 10;
  } as_s;
} XcandmhcregTxscanbcUt;

#define RESET_VAL_XCAND_MH_CREG_TX_SCAN_BC 0x00000000


#define XCAND_MH_CREG_TX_SCAN_BC_FH_PQ_MASK 0x1
#define XCAND_MH_CREG_TX_SCAN_BC_FH_PQ_SHIFT 0

#define XCAND_MH_CREG_TX_SCAN_BC_FH_FQN_PQSN_MASK 0x3e
#define XCAND_MH_CREG_TX_SCAN_BC_FH_FQN_PQSN_SHIFT 1

#define XCAND_MH_CREG_TX_SCAN_BC_FH_OFFSET_MASK 0xffc0
#define XCAND_MH_CREG_TX_SCAN_BC_FH_OFFSET_SHIFT 6

#define XCAND_MH_CREG_TX_SCAN_BC_SH_PQ_MASK 0x10000
#define XCAND_MH_CREG_TX_SCAN_BC_SH_PQ_SHIFT 16

#define XCAND_MH_CREG_TX_SCAN_BC_SH_FQN_PQSN_MASK 0x3e0000
#define XCAND_MH_CREG_TX_SCAN_BC_SH_FQN_PQSN_SHIFT 17

#define XCAND_MH_CREG_TX_SCAN_BC_SH_OFFSET_MASK 0xffc00000
#define XCAND_MH_CREG_TX_SCAN_BC_SH_OFFSET_SHIFT 22

//Register: TX_FQ_DESC_VALID Addr: 0x818
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DesccnvalidU8 : 8;
    uint32_t reserved8_u8 : 8;
    uint32_t DescncvalidU8 : 8;
    uint32_t reserved24_u8 : 8;
  } as_s;
} XcandmhcregTxfqdescvalidUt;

#define RESET_VAL_XCAND_MH_CREG_TX_FQ_DESC_VALID 0x00000000


#define XCAND_MH_CREG_TX_FQ_DESC_VALID_DESC_CN_VALID_MASK 0xff
#define XCAND_MH_CREG_TX_FQ_DESC_VALID_DESC_CN_VALID_SHIFT 0

#define XCAND_MH_CREG_TX_FQ_DESC_VALID_DESC_NC_VALID_MASK 0xff0000
#define XCAND_MH_CREG_TX_FQ_DESC_VALID_DESC_NC_VALID_SHIFT 16

//Register: TX_PQ_DESC_VALID Addr: 0x81C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DescvalidU32 : 32;
  } as_s;
} XcandmhcregTxpqdescvalidUt;

#define RESET_VAL_XCAND_MH_CREG_TX_PQ_DESC_VALID 0x00000000


#define XCAND_MH_CREG_TX_PQ_DESC_VALID_DESC_VALID_MASK 0xffffffff
#define XCAND_MH_CREG_TX_PQ_DESC_VALID_DESC_VALID_SHIFT 0

//Register: CRC_CTRL Addr: 0x880
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t StartU1 : 1;
    uint32_t reserved1_u31 : 31;
  } as_s;
} XcandmhcregCrcctrlUt;

#define RESET_VAL_XCAND_MH_CREG_CRC_CTRL 0x00000000


#define XCAND_MH_CREG_CRC_CTRL_START_MASK 0x1
#define XCAND_MH_CREG_CRC_CTRL_START_SHIFT 0

//Register: CRC_REG Addr: 0x884
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ValU32 : 32;
  } as_s;
} XcandmhcregCrcregUt;

#define RESET_VAL_XCAND_MH_CREG_CRC_REG 0x00000000


#define XCAND_MH_CREG_CRC_REG_VAL_MASK 0xffffffff
#define XCAND_MH_CREG_CRC_REG_VAL_SHIFT 0

/*===========================================================================
 * TX/RX Descriptor Structures and Word Unions
 * (from xcand_mh_regdef.h)
 *==========================================================================*/

#ifndef BIT
#define BIT(x) (1 << (x))
#endif

#ifndef BITMASK_FROM_B_DOWNTO_A
#define BITMASK_FROM_B_DOWNTO_A(b, a) (((unsigned) -1 >> (31 - (b))) & ~((1U << (a)) - 1))
#endif


/* === TX DESCRIPTOR ========================================================= */

/* TX DESCRIPTOR Element (Word) 0 */
#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* Little Endian = start bit field with Bit 0 of the word */
    uint32_t STSu4              :  4; /*  3: 0 Status of the transmitted frame */
    uint32_t RCu5               :  5; /*  8: 4 Rolling Counter */
    uint32_t res1u2             :  2; /* 10: 9 Reserved, set to 0 */
    uint32_t res0u1             :  1; /*    11 reserved */
    uint32_t FQNu4              :  4; /* 15:12 TX FIFO Queue Number */
    uint32_t CRCu9              :  9; /* 24:16 DESC CRC */
    uint32_t ENDu1              :  1; /*    25 END */
    uint32_t PQu1               :  1; /*    26 0= TX FIFO Queue, 1= TX Priority Queue */
    uint32_t IRQu1              :  1; /*    27 Interrupt */
    uint32_t NEXTu1             :  1; /*    28 Next */
    uint32_t WRAPu1             :  1; /*    29 Wrap */
    uint32_t HDu1               :  1; /*    30 Header Descriptor of Frame */
    uint32_t VALIDu1            :  1; /*    31 Valid */
  } as_TX_FIFO_Queue;
  struct
  { /* Little Endian = start bit field with Bit 0 of the word */
    uint32_t STSu4              :  4; /*  3: 0 Status */
    uint32_t RCu5               :  5; /*  8: 4 Rolling Counter */
    uint32_t res0u2             :  2; /* 10: 9 Reserved, set to 0 */
    uint32_t PQSNu5             :  5; /* 15:11 TX Priority Queue Slot Number */
    uint32_t CRCu9              :  9; /* 24:16 DESC CRC */
    uint32_t ENDu1              :  1; /*    25 END */
    uint32_t PQu1               :  1; /*    26 0= TX FIFO Queue, 1= TX Priority Queue */
    uint32_t IRQu1              :  1; /*    27 Interrupt */
    uint32_t NEXTu1             :  1; /*    28 Next */
    uint32_t WRAPu1             :  1; /*    29 Wrap */
    uint32_t HDu1               :  1; /*    30 Header Descriptor of Frame */
    uint32_t VALIDu1            :  1; /*    31 Valid */
  } as_TX_PRIO_Queue;
} XCAND_MH_TX_DESC_ELEM0_union;
#endif

/* TX DESCRIPTOR Element (Word) 1 */
#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* Little Endian = start bit field with Bit 0 of the word */
    uint32_t res2u2             :  2; /*  1: 0 reserved */
    uint32_t NHDOu10            : 10; /* 11: 2 Next Header Descriptor Offset */
    uint32_t res1u1             :  1; /*    12 reserved */
    uint32_t INu3               :  3; /* 15:13 XCAND Instance number */
    uint32_t SIZEu10            : 10; /* 25:16 Number of valid data words in data container */
    uint32_t PLSRCu1            :  1; /*    26 Payload Source */
    uint32_t res0u5             :  5; /* 31:27 reserved */
  } as_TX_FIFO_Queue;
  struct
  { /* Little Endian = start bit field with Bit 0 of the word */
    uint32_t res2u2             :  2; /*  1: 0 reserved */
    uint32_t TDOu10             : 10; /* 11: 2 Trailing Descriptor Offset */
    uint32_t res1u1             :  1; /*    12 reserved */
    uint32_t INu3               :  3; /* 15:13 XCAND Instance number */
    uint32_t SIZEu10            : 10; /* 25:16 Number of valid data words in data container */
    uint32_t PLSRCu1            :  1; /*    26 Payload Source */
    uint32_t res0u5             :  5; /* 31:27 reserved */
  } as_TX_PRIO_Queue;
} XCAND_MH_TX_DESC_ELEM1_union;
#endif

/* TX Word 0 (according MH_PRT_IF Spec) */
#define TX_W0_FDF_MASK     BIT(31)
#define TX_W0_FDF_SHIFT    31
#define TX_W0_XLF_MASK     BIT(30)
#define TX_W0_XLF_SHIFT    30

#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* CC/FD Base Identifier */
    uint32_t resu18             : 18; /* 17.. 0 Reserved */
    uint32_t IDBASEu11          : 11; /* 28..18 Base Identifier */
    uint32_t XTDu1              :  1; /* 29     Extended Identifier Marker */
    uint32_t XLFu1              :  1; /* 30     XL Format */
    uint32_t FDFu1              :  1; /* 31     FD Format */
  } as_ccfd_id_base;
  struct
  { /* CC/FD Extended Identifier */
    uint32_t IDEXTu29           : 29; /* 28.. 0 Extended Identifier */
    uint32_t XTDu1              :  1; /* 29     Extended Identifier Marker */
    uint32_t XLFu1              :  1; /* 30     XL Format */
    uint32_t FDFu1              :  1; /* 31     FD Format */
  } as_ccfd_id_ext;
  struct
  { /* CAN XL */
    uint32_t SDTu8              :  8; /*  7.. 0 SDU Type */
    uint32_t VCIDu8             :  8; /* 15.. 8 Virtual CAN Network ID */
    uint32_t SECu1              :  1; /* 16     SEC bit */
    uint32_t RRSu1              :  1; /* 17     RRS bit */
    uint32_t IDPRIOu11          : 11; /* 28..18 Priority Identifier */
    uint32_t resu1              :  1; /* 29     Reserved */
    uint32_t XLFu1              :  1; /* 30     XL Format */
    uint32_t FDFu1              :  1; /* 31     FD Format */
  } as_xl;
} XCAND_MH_TX_W0_union;
#endif

/* TX Word 1 (according MH_PRT_IF Spec) */
#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* CC/FD */
    uint32_t resu16             : 16; /* 15.. 0 Reserved */
    uint32_t DLCu4              :  4; /* 19..16 Data Length Code */
    uint32_t ESIu1              :  1; /* 20     Error State Indicator */
    uint32_t resu4              :  4; /* 24..21 Reserved */
    uint32_t BRSu1              :  1; /* 25     Bit Rate Switch */
    uint32_t RTRu1              :  1; /* 26     Remote Transmission Request */
    uint32_t resu3              :  3; /* 29..27 Reserved */
    uint32_t FIRu1              :  1; /* 30     Fault Injection Request */
    uint32_t resu1              :  1; /* 31     Reserved */
  } as_ccfd;
  struct
  { /* CAN XL */
    uint32_t resu16             : 16; /* 15.. 0 Reserved */
    uint32_t DLCu11             : 11; /* 26..16 Data Length Code */
    uint32_t resu3              :  3; /* 29..27 Reserved */
    uint32_t FIRu1              :  1; /* 30     Fault Injection Request */
    uint32_t resu1              :  1; /* 31     Reserved */
  } as_xl;
} XCAND_MH_TX_W1_union;
#endif


/* TX DESCRIPTOR struct: Element6 */
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t                     T2;            /* Frame header W2: Acceptance Field (AF) */
  } as_xl;
  struct
  {
    uint32_t                     TD0;           /* Frame data word 0 */
  } as_ccfd;
} XCAND_MH_TX_DESC_elem6_union;

/* TX DESCRIPTOR struct: Element7 */
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t                     TX_AP;         /* CAN XL and CAN FD with payload > 4 bytes: address pointer to data container */
  } as_fdxl;
  struct
  {
    uint32_t                     TD1;           /* Frame data word 1 */
  } as_cc;
} XCAND_MH_TX_DESC_elem7_union;

/* TX DESCRIPTOR struct */
typedef volatile struct {
    XCAND_MH_TX_DESC_ELEM0_union elem0;         /* Element (Word) 0 of TX Descriptor */
    XCAND_MH_TX_DESC_ELEM1_union elem1;         /* Element (Word) 1 of TX Descriptor */
    uint32_t                     elem2_ts_lsw;  /* TimeStamp LSW */
    uint32_t                     elem3_ts_msw;  /* TimeStamp MSW */
    XCAND_MH_TX_W0_union         elem4_T0;      /* Frame header W0 */
    XCAND_MH_TX_W1_union         elem5_T1;      /* Frame header W1 */
    XCAND_MH_TX_DESC_elem6_union elem6;         /* Frame header W2 (AF) or TD0 */
    XCAND_MH_TX_DESC_elem7_union elem7;         /* CC: TD1, FD/XL: address pointer to data container */
} XCAND_MH_TX_DESC_struct;



/* === RX DESCRIPTOR ========================================================= */

/* RX DESCRIPTOR Element (Word) 0 */
#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* Little Endian = start bit field with Bit 0 of the word */
    uint32_t STSu4              :  4; /*  3:00 Status of the received frame */
    uint32_t RCu5               :  5; /*  8:04 Rolling Counter */
    uint32_t INu3               :  3; /* 11:09 XCAND Instance number */
    uint32_t FQNu4              :  4; /* 15:12 RX FIFO Queue Number */
    uint32_t CRCu7              :  7; /* 22:16 DESC CRC */
    uint32_t res1u4             :  4; /* 26:23 reserved, must be set to 0 */
    uint32_t IRQu1              :  1; /*    27 Interrupt */
    uint32_t NEXTu1             :  1; /*    28 Next */
    uint32_t res0u1             :  1; /*    29 reserved */
    uint32_t HDu1               :  1; /*    30 Header Descriptor of Frame */
    uint32_t VALIDu1            :  1; /*    31 Valid */
  } as_RX_FIFO_Queue;
} XCAND_MH_RX_DESC_ELEM0_union;
#endif

/* RX DESCRIPTOR struct */
typedef volatile struct
{
    XCAND_MH_RX_DESC_ELEM0_union elem0;         /* Element (Word) 0 of RX Descriptor */
    uint32_t                     elem1_rx_ap;   /* RX data container address pointer */
    uint32_t                     elem2_ts_lsw;  /* TimeStamp LSW */
    uint32_t                     elem3_ts_msw;  /* TimeStamp MSW */
} XCAND_MH_RX_DESC_struct;


/* RX Word 0 (according MH_PRT_IF Spec) */
#define RXF_R0_FDF_MASK     BIT(31)
#define RXF_R0_FDF_SHIFT    31
#define RXF_R0_XLF_MASK     BIT(30)
#define RXF_R0_XLF_SHIFT    30

#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* CC/FD Base Identifier */
    uint32_t resu18             : 18; /* 17.. 0 Reserved */
    uint32_t IDBASEu11          : 11; /* 28..18 Base Identifier */
    uint32_t XTDu1              :  1; /* 29     Extended Identifier Marker */
    uint32_t XLFu1              :  1; /* 30     XL Format */
    uint32_t FDFu1              :  1; /* 31     FD Format */
  } as_ccfd_id_base;
  struct
  { /* CC/FD Extended Identifier */
    uint32_t IDEXTu29           : 29; /* 28.. 0 Extended Identifier */
    uint32_t XTDu1              :  1; /* 29     Extended Identifier Marker */
    uint32_t XLFu1              :  1; /* 30     XL Format */
    uint32_t FDFu1              :  1; /* 31     FD Format */
  } as_ccfd_id_ext;
  struct
  { /* CAN XL */
    uint32_t SDTu8              :  8; /*  7.. 0 SDU Type */
    uint32_t VCIDu8             :  8; /* 15.. 8 Virtual CAN Network ID */
    uint32_t SECu1              :  1; /* 16     SEC bit */
    uint32_t RRSu1              :  1; /* 17     RRS bit */
    uint32_t IDPRIOu11          : 11; /* 28..18 Priority Identifier */
    uint32_t resu1              :  1; /* 29     Reserved */
    uint32_t XLFu1              :  1; /* 30     XL Format */
    uint32_t FDFu1              :  1; /* 31     FD Format */
  } as_xl;
} XCAND_MH_RX_R0_union;
#endif

/* RX Word 1 (according MH_PRT_IF Spec + some more bits from MH) */
#if __LITTLE_ENDIAN
typedef volatile union
{
  uint32_t as_uint32;
  struct
  { /* CC/FD */
    uint32_t FIDXu8             :  8; /* 07..00 RX Filter Element Index */
    uint32_t FMu1               :  1; /*     08 RX Filter Matched */
    uint32_t BLKu1              :  1; /*     09 RX Filter Blacklisted */
    uint32_t FABu1              :  1; /*     10 RX Filtering Aborted */
    uint32_t res1u5             :  5; /* 15..11 Reserved */
    uint32_t DLCu4              :  4; /* 19..16 Data Length Code */
    uint32_t ESIu1              :  1; /* 20     Error State Indicator */
    uint32_t resu4              :  4; /* 24..21 Reserved */
    uint32_t BRSu1              :  1; /* 25     Bit Rate Switch */
    uint32_t RTRu1              :  1; /* 26     Remote Transmission Request */
    uint32_t res0u5             :  5; /* 31..27 Reserved */
  } as_ccfd;
  struct
  { /* CAN XL */
    uint32_t FIDXu8             :  8; /* 07..00 RX Filter Element Index */
    uint32_t FMu1               :  1; /*     08 RX Filter Matched */
    uint32_t BLKu1              :  1; /*     09 RX Filter Blacklisted */
    uint32_t FABu1              :  1; /*     10 RX Filtering Aborted */
    uint32_t res1u5             :  5; /* 15..11 Reserved */
    uint32_t DLCu11             : 11; /* 26..16 Data Length Code */
    uint32_t res0u5             :  5; /* 31..27 Reserved */
  } as_xl;
} XCAND_MH_RX_R1_union;
#endif


/* === RX FILTER Element ===================================================== */
typedef union {
  uint32_t as_uint32;
  struct{
    uint32_t CREFI0u8           :  8; /* 00..07 Comparison Reference Index 0 */
    uint32_t WI0u2              :  2; /* 08..09 Word Index 0 */
    uint32_t AR0u1              :  1; /*     10 Accept or reject on match 0 */
    uint32_t res1u1             :  1; /*     11 */
    uint32_t CREFI1u8           :  8; /* 12..19 Comparison Reference Index 1 */
    uint32_t WI1u2              :  2; /* 20..21 Word Index 1 */
    uint32_t AR1u1              :  1; /*     22 Accept or reject on match 1 */
    uint32_t res0u3             :  3; /* 23..25 */
    uint32_t BLKu1              :  1; /*     26 BlackList */
    uint32_t IRQu1              :  1; /*     27 Interrupt */
    uint32_t FIFOu4             :  4; /* 28..31 RX FIFO Queue number */
  } as_s;
} XCAND_MH_RX_FILTER_ELEMENT_UNION;


#endif /* XCAN_MH_REGDEF_H */
