/*
 * XCAN PRT (Protocol Controller) Register Definitions
 *
 * Merged from xcan_prt_reg_PRT_MAP_memoryMap.h and xcan_prt_regdef.h
 * Originally auto-generated by RegMan from IP-XACT description.
 * Adapted for AUTOSAR driver: platform-specific constructs removed.
 *
 * Source: xcan_sw_example (Robert Bosch GmbH)
 * Original RegMan version: v2009_009h2, Created: 09.08.2022
 */

#ifndef XCAN_PRT_REGDEF_H
#define XCAN_PRT_REGDEF_H

#include "xcan_platform.h"


/*-----------------------------------------------------------------------------
 * constants: MemoryMap PRT_MAP of Component xcan_prt_reg
 *---------------------------------------------------------------------------*/
#define PRT_MAP_LAST_ADDR 0x7c
#define PRT_MAP_ADDR_SPACE 0x80
#define PRT_MAP_ADDR_SPACE_ALIGNED 0x100
#define PRT_MAP_DATA_WIDTH 32
#define PRT_MAP_ADDR_UNIT_BITS 8
#define PRT_MAP_ADDR_STEP 4

/*-----------------------------------------------------------------------------
* constants: absolute addresses of address Blocks
*---------------------------------------------------------------------------*/

#define STATUS_BASE_ADDR 0x00UL
#define STATUS_LENGTH 0x20UL
#define STATUS_LAST_ADDR 0x1FUL

#define EVENT_BASE_ADDR 0x20UL
#define EVENT_LENGTH 0x20UL
#define EVENT_LAST_ADDR 0x3FUL

#define CONTROL_BASE_ADDR 0x40UL
#define CONTROL_LENGTH 0x20UL
#define CONTROL_LAST_ADDR 0x5FUL

#define CONFIGURATION_BASE_ADDR 0x60UL
#define CONFIGURATION_LENGTH 0x20UL
#define CONFIGURATION_LAST_ADDR 0x7FUL

/*-----------------------------------------------------------------------------
* constants: absolute addresses of address Blocks
*---------------------------------------------------------------------------*/
#define STATUS_ENDN                              0x00
#define STATUS_PREL                              0x04
#define STATUS_STAT                              0x08
#define EVENT_EVNT                               0x20
#define CONTROL_LOCK                             0x40
#define CONTROL_CTRL                             0x44
#define CONTROL_FIMC                             0x48
#define CONTROL_TEST                             0x4C
#define CONFIGURATION_MODE                       0x60
#define CONFIGURATION_NBTP                       0x64
#define CONFIGURATION_DBTP                       0x68
#define CONFIGURATION_XBTP                       0x6C
#define CONFIGURATION_PCFG                       0x70


/*-----------------------------------------------------------------------------
 * Register bit-field union types
 *---------------------------------------------------------------------------*/


/*-----------------------------------------------------------------------------
 * Register specific bit fields
 *---------------------------------------------------------------------------*/

//Register: ENDN Addr: 0x00
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t EtvU32 : 32;
  } as_s;
} StatusEndnUt;

#define RESET_VAL_STATUS_ENDN 0x87654321


#define STATUS_ENDN_ETV_MASK 0xffffffff
#define STATUS_ENDN_ETV_SHIFT 0

//Register: PREL Addr: 0x04
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DayU8 : 8;
    uint32_t MonU8 : 8;
    uint32_t YearU4 : 4;
    uint32_t SubstepU4 : 4;
    uint32_t StepU4 : 4;
    uint32_t RelU4 : 4;
  } as_s;
} StatusPrelUt;

#define RESET_VAL_STATUS_PREL 0x05421103


#define STATUS_PREL_DAY_MASK 0xff
#define STATUS_PREL_DAY_SHIFT 0

#define STATUS_PREL_MON_MASK 0xff00
#define STATUS_PREL_MON_SHIFT 8

#define STATUS_PREL_YEAR_MASK 0xf0000
#define STATUS_PREL_YEAR_SHIFT 16

#define STATUS_PREL_SUBSTEP_MASK 0xf00000
#define STATUS_PREL_SUBSTEP_SHIFT 20

#define STATUS_PREL_STEP_MASK 0xf000000
#define STATUS_PREL_STEP_SHIFT 24

#define STATUS_PREL_REL_MASK 0xf0000000
#define STATUS_PREL_REL_SHIFT 28

//Register: STAT Addr: 0x08
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t ActU2 : 2;
    uint32_t IntU1 : 1;
    uint32_t StpU1 : 1;
    uint32_t ClkaU1 : 1;
    uint32_t FimaU1 : 1;
    uint32_t EpU1 : 1;
    uint32_t BoU1 : 1;
    uint32_t TdcvU8 : 8;
    uint32_t RecU7 : 7;
    uint32_t RpU1 : 1;
    uint32_t TecU8 : 8;
  } as_s;
} StatusStatUt;

#define RESET_VAL_STATUS_STAT 0x00000010


#define STATUS_STAT_ACT_MASK 0x3
#define STATUS_STAT_ACT_SHIFT 0

#define STATUS_STAT_INT_MASK 0x4
#define STATUS_STAT_INT_SHIFT 2

#define STATUS_STAT_STP_MASK 0x8
#define STATUS_STAT_STP_SHIFT 3

#define STATUS_STAT_CLKA_MASK 0x10
#define STATUS_STAT_CLKA_SHIFT 4

#define STATUS_STAT_FIMA_MASK 0x20
#define STATUS_STAT_FIMA_SHIFT 5

#define STATUS_STAT_EP_MASK 0x40
#define STATUS_STAT_EP_SHIFT 6

#define STATUS_STAT_BO_MASK 0x80
#define STATUS_STAT_BO_SHIFT 7

#define STATUS_STAT_TDCV_MASK 0xff00
#define STATUS_STAT_TDCV_SHIFT 8

#define STATUS_STAT_REC_MASK 0x7f0000
#define STATUS_STAT_REC_SHIFT 16

#define STATUS_STAT_RP_MASK 0x800000
#define STATUS_STAT_RP_SHIFT 23

#define STATUS_STAT_TEC_MASK 0xff000000
#define STATUS_STAT_TEC_SHIFT 24

//Register: EVNT Addr: 0x20
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t CreU1 : 1;
    uint32_t B0eU1 : 1;
    uint32_t B1eU1 : 1;
    uint32_t AkeU1 : 1;
    uint32_t FreU1 : 1;
    uint32_t SteU1 : 1;
    uint32_t DoU1 : 1;
    uint32_t RxfU1 : 1;
    uint32_t TxfU1 : 1;
    uint32_t PxeU1 : 1;
    uint32_t DuU1 : 1;
    uint32_t UsoU1 : 1;
    uint32_t IfrU1 : 1;
    uint32_t AboU1 : 1;
    uint32_t reserved14_u18 : 18;
  } as_s;
} EventEvntUt;

#define RESET_VAL_EVENT_EVNT 0x00000000


#define EVENT_EVNT_CRE_MASK 0x1
#define EVENT_EVNT_CRE_SHIFT 0

#define EVENT_EVNT_B0E_MASK 0x2
#define EVENT_EVNT_B0E_SHIFT 1

#define EVENT_EVNT_B1E_MASK 0x4
#define EVENT_EVNT_B1E_SHIFT 2

#define EVENT_EVNT_AKE_MASK 0x8
#define EVENT_EVNT_AKE_SHIFT 3

#define EVENT_EVNT_FRE_MASK 0x10
#define EVENT_EVNT_FRE_SHIFT 4

#define EVENT_EVNT_STE_MASK 0x20
#define EVENT_EVNT_STE_SHIFT 5

#define EVENT_EVNT_DO_MASK 0x40
#define EVENT_EVNT_DO_SHIFT 6

#define EVENT_EVNT_RXF_MASK 0x80
#define EVENT_EVNT_RXF_SHIFT 7

#define EVENT_EVNT_TXF_MASK 0x100
#define EVENT_EVNT_TXF_SHIFT 8

#define EVENT_EVNT_PXE_MASK 0x200
#define EVENT_EVNT_PXE_SHIFT 9

#define EVENT_EVNT_DU_MASK 0x400
#define EVENT_EVNT_DU_SHIFT 10

#define EVENT_EVNT_USO_MASK 0x800
#define EVENT_EVNT_USO_SHIFT 11

#define EVENT_EVNT_IFR_MASK 0x1000
#define EVENT_EVNT_IFR_SHIFT 12

#define EVENT_EVNT_ABO_MASK 0x2000
#define EVENT_EVNT_ABO_SHIFT 13

//Register: LOCK Addr: 0x40
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t UlkU16 : 16;
    uint32_t TmkU16 : 16;
  } as_s;
} ControlLockUt;

#define RESET_VAL_CONTROL_LOCK 0x00000000


#define CONTROL_LOCK_ULK_MASK 0xffff
#define CONTROL_LOCK_ULK_SHIFT 0

#define CONTROL_LOCK_TMK_MASK 0xffff0000
#define CONTROL_LOCK_TMK_SHIFT 16

//Register: CTRL Addr: 0x44
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t StopU1 : 1;
    uint32_t ImmdU1 : 1;
    uint32_t reserved2_u2 : 2;
    uint32_t StrtU1 : 1;
    uint32_t reserved5_u3 : 3;
    uint32_t SresU1 : 1;
    uint32_t reserved9_u3 : 3;
    uint32_t TestU1 : 1;
    uint32_t reserved13_u19 : 19;
  } as_s;
} ControlCtrlUt;

#define RESET_VAL_CONTROL_CTRL 0x00000000


#define CONTROL_CTRL_STOP_MASK 0x1
#define CONTROL_CTRL_STOP_SHIFT 0

#define CONTROL_CTRL_IMMD_MASK 0x2
#define CONTROL_CTRL_IMMD_SHIFT 1

#define CONTROL_CTRL_STRT_MASK 0x10
#define CONTROL_CTRL_STRT_SHIFT 4

#define CONTROL_CTRL_SRES_MASK 0x100
#define CONTROL_CTRL_SRES_SHIFT 8

#define CONTROL_CTRL_TEST_MASK 0x1000
#define CONTROL_CTRL_TEST_SHIFT 12

//Register: FIMC Addr: 0x48
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FipU15 : 15;
    uint32_t reserved15_u17 : 17;
  } as_s;
} ControlFimcUt;

#define RESET_VAL_CONTROL_FIMC 0x00000000


#define CONTROL_FIMC_FIP_MASK 0x7fff
#define CONTROL_FIMC_FIP_SHIFT 0

//Register: TEST Addr: 0x4C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t LbckU1 : 1;
    uint32_t reserved1_u2 : 2;
    uint32_t RxdU1 : 1;
    uint32_t TxcU2 : 2;
    uint32_t reserved6_u9 : 9;
    uint32_t HwtU1 : 1;
    uint32_t AbortedU1 : 1;
    uint32_t UsosU1 : 1;
    uint32_t TxduU1 : 1;
    uint32_t RxdoU1 : 1;
    uint32_t IffrqU1 : 1;
    uint32_t TxevtU1 : 1;
    uint32_t RxevtU1 : 1;
    uint32_t BuserrU1 : 1;
    uint32_t EactiveU1 : 1;
    uint32_t EpassiveU1 : 1;
    uint32_t BusonU1 : 1;
    uint32_t BusoffU1 : 1;
    uint32_t reserved28_u4 : 4;
  } as_s;
} ControlTestUt;

#define RESET_VAL_CONTROL_TEST 0x00000008


#define CONTROL_TEST_LBCK_MASK 0x1
#define CONTROL_TEST_LBCK_SHIFT 0

#define CONTROL_TEST_RXD_MASK 0x8
#define CONTROL_TEST_RXD_SHIFT 3

#define CONTROL_TEST_TXC_MASK 0x30
#define CONTROL_TEST_TXC_SHIFT 4

#define CONTROL_TEST_HWT_MASK 0x8000
#define CONTROL_TEST_HWT_SHIFT 15

#define CONTROL_TEST_ABORTED_MASK 0x10000
#define CONTROL_TEST_ABORTED_SHIFT 16

#define CONTROL_TEST_USOS_MASK 0x20000
#define CONTROL_TEST_USOS_SHIFT 17

#define CONTROL_TEST_TX_DU_MASK 0x40000
#define CONTROL_TEST_TX_DU_SHIFT 18

#define CONTROL_TEST_RX_DO_MASK 0x80000
#define CONTROL_TEST_RX_DO_SHIFT 19

#define CONTROL_TEST_IFF_RQ_MASK 0x100000
#define CONTROL_TEST_IFF_RQ_SHIFT 20

#define CONTROL_TEST_TX_EVT_MASK 0x200000
#define CONTROL_TEST_TX_EVT_SHIFT 21

#define CONTROL_TEST_RX_EVT_MASK 0x400000
#define CONTROL_TEST_RX_EVT_SHIFT 22

#define CONTROL_TEST_BUS_ERR_MASK 0x800000
#define CONTROL_TEST_BUS_ERR_SHIFT 23

#define CONTROL_TEST_E_ACTIVE_MASK 0x1000000
#define CONTROL_TEST_E_ACTIVE_SHIFT 24

#define CONTROL_TEST_E_PASSIVE_MASK 0x2000000
#define CONTROL_TEST_E_PASSIVE_SHIFT 25

#define CONTROL_TEST_BUS_ON_MASK 0x4000000
#define CONTROL_TEST_BUS_ON_SHIFT 26

#define CONTROL_TEST_BUS_OFF_MASK 0x8000000
#define CONTROL_TEST_BUS_OFF_SHIFT 27

//Register: MODE Addr: 0x60
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FdoeU1 : 1;
    uint32_t XloeU1 : 1;
    uint32_t TdceU1 : 1;
    uint32_t PxhdU1 : 1;
    uint32_t EfbiU1 : 1;
    uint32_t TxpU1 : 1;
    uint32_t MonU1 : 1;
    uint32_t RstrU1 : 1;
    uint32_t SfsU1 : 1;
    uint32_t XltrU1 : 1;
    uint32_t EfdiU1 : 1;
    uint32_t FimeU1 : 1;
    uint32_t reserved12_u20 : 20;
  } as_s;
} ConfigurationModeUt;

#define RESET_VAL_CONFIGURATION_MODE 0x00000000


#define CONFIGURATION_MODE_FDOE_MASK 0x1
#define CONFIGURATION_MODE_FDOE_SHIFT 0

#define CONFIGURATION_MODE_XLOE_MASK 0x2
#define CONFIGURATION_MODE_XLOE_SHIFT 1

#define CONFIGURATION_MODE_TDCE_MASK 0x4
#define CONFIGURATION_MODE_TDCE_SHIFT 2

#define CONFIGURATION_MODE_PXHD_MASK 0x8
#define CONFIGURATION_MODE_PXHD_SHIFT 3

#define CONFIGURATION_MODE_EFBI_MASK 0x10
#define CONFIGURATION_MODE_EFBI_SHIFT 4

#define CONFIGURATION_MODE_TXP_MASK 0x20
#define CONFIGURATION_MODE_TXP_SHIFT 5

#define CONFIGURATION_MODE_MON_MASK 0x40
#define CONFIGURATION_MODE_MON_SHIFT 6

#define CONFIGURATION_MODE_RSTR_MASK 0x80
#define CONFIGURATION_MODE_RSTR_SHIFT 7

#define CONFIGURATION_MODE_SFS_MASK 0x100
#define CONFIGURATION_MODE_SFS_SHIFT 8

#define CONFIGURATION_MODE_XLTR_MASK 0x200
#define CONFIGURATION_MODE_XLTR_SHIFT 9

#define CONFIGURATION_MODE_EFDI_MASK 0x400
#define CONFIGURATION_MODE_EFDI_SHIFT 10

#define CONFIGURATION_MODE_FIME_MASK 0x800
#define CONFIGURATION_MODE_FIME_SHIFT 11

//Register: NBTP Addr: 0x64
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t NsjwU7 : 7;
    uint32_t reserved7_u1 : 1;
    uint32_t Ntseg2U7 : 7;
    uint32_t reserved15_u1 : 1;
    uint32_t Ntseg1U9 : 9;
    uint32_t BrpU5 : 5;
    uint32_t reserved30_u2 : 2;
  } as_s;
} ConfigurationNbtpUt;

#define RESET_VAL_CONFIGURATION_NBTP 0x00000000


#define CONFIGURATION_NBTP_NSJW_MASK 0x7f
#define CONFIGURATION_NBTP_NSJW_SHIFT 0

#define CONFIGURATION_NBTP_NTSEG2_MASK 0x7f00
#define CONFIGURATION_NBTP_NTSEG2_SHIFT 8

#define CONFIGURATION_NBTP_NTSEG1_MASK 0x1ff0000
#define CONFIGURATION_NBTP_NTSEG1_SHIFT 16

#define CONFIGURATION_NBTP_BRP_MASK 0x3e000000
#define CONFIGURATION_NBTP_BRP_SHIFT 25

//Register: DBTP Addr: 0x68
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t DsjwU7 : 7;
    uint32_t reserved7_u1 : 1;
    uint32_t Dtseg2U7 : 7;
    uint32_t reserved15_u1 : 1;
    uint32_t Dtseg1U8 : 8;
    uint32_t DtdcoU8 : 8;
  } as_s;
} ConfigurationDbtpUt;

#define RESET_VAL_CONFIGURATION_DBTP 0x00000000


#define CONFIGURATION_DBTP_DSJW_MASK 0x7f
#define CONFIGURATION_DBTP_DSJW_SHIFT 0

#define CONFIGURATION_DBTP_DTSEG2_MASK 0x7f00
#define CONFIGURATION_DBTP_DTSEG2_SHIFT 8

#define CONFIGURATION_DBTP_DTSEG1_MASK 0xff0000
#define CONFIGURATION_DBTP_DTSEG1_SHIFT 16

#define CONFIGURATION_DBTP_DTDCO_MASK 0xff000000
#define CONFIGURATION_DBTP_DTDCO_SHIFT 24

//Register: XBTP Addr: 0x6C
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t XsjwU7 : 7;
    uint32_t reserved7_u1 : 1;
    uint32_t Xtseg2U7 : 7;
    uint32_t reserved15_u1 : 1;
    uint32_t Xtseg1U8 : 8;
    uint32_t XtdcoU8 : 8;
  } as_s;
} ConfigurationXbtpUt;

#define RESET_VAL_CONFIGURATION_XBTP 0x00000000


#define CONFIGURATION_XBTP_XSJW_MASK 0x7f
#define CONFIGURATION_XBTP_XSJW_SHIFT 0

#define CONFIGURATION_XBTP_XTSEG2_MASK 0x7f00
#define CONFIGURATION_XBTP_XTSEG2_SHIFT 8

#define CONFIGURATION_XBTP_XTSEG1_MASK 0xff0000
#define CONFIGURATION_XBTP_XTSEG1_SHIFT 16

#define CONFIGURATION_XBTP_XTDCO_MASK 0xff000000
#define CONFIGURATION_XBTP_XTDCO_SHIFT 24

//Register: PCFG Addr: 0x70
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t PwmsU6 : 6;
    uint32_t reserved6_u2 : 2;
    uint32_t PwmlU6 : 6;
    uint32_t reserved14_u2 : 2;
    uint32_t PwmoU6 : 6;
    uint32_t reserved22_u10 : 10;
  } as_s;
} ConfigurationPcfgUt;

#define RESET_VAL_CONFIGURATION_PCFG 0x00000000


#define CONFIGURATION_PCFG_PWMS_MASK 0x3f
#define CONFIGURATION_PCFG_PWMS_SHIFT 0

#define CONFIGURATION_PCFG_PWML_MASK 0x3f00
#define CONFIGURATION_PCFG_PWML_SHIFT 8

#define CONFIGURATION_PCFG_PWMO_MASK 0x3f0000
#define CONFIGURATION_PCFG_PWMO_SHIFT 16

#endif /* XCAN_PRT_REGDEF_H */
