/*
 * XCAN IRC (Interrupt Controller) Register Definitions
 *
 * Merged from xcand_top_irc_IRC_MAP_memoryMap.h and xcand_irc_regdef.h
 * Originally auto-generated by RegMan from IP-XACT description.
 * Adapted for AUTOSAR driver: platform-specific constructs removed.
 *
 * Source: xcan_sw_example (Robert Bosch GmbH)
 * Original RegMan version: v2009_009h2, Created: 09.08.2022
 */

#ifndef XCAN_IRC_REGDEF_H
#define XCAN_IRC_REGDEF_H

#include "xcan_platform.h"


/*-----------------------------------------------------------------------------
 * constants: MemoryMap IRC_MAP of Component xcand_top_irc
 *---------------------------------------------------------------------------*/
#define IRC_MAP_LAST_ADDR 0xec
#define IRC_MAP_ADDR_SPACE 0xf0
#define IRC_MAP_ADDR_SPACE_ALIGNED 0x100
#define IRC_MAP_DATA_WIDTH 32
#define IRC_MAP_ADDR_UNIT_BITS 8
#define IRC_MAP_ADDR_STEP 4

/*-----------------------------------------------------------------------------
* constants: absolute addresses of address Blocks
*---------------------------------------------------------------------------*/

//#define EVENT_BASE_ADDR 0x00UL
//#define EVENT_LENGTH 0x10UL
//#define EVENT_LAST_ADDR 0x0FUL
//
//#define CONTROL_BASE_ADDR 0x10UL
//#define CONTROL_LENGTH 0x20UL
//#define CONTROL_LAST_ADDR 0x2FUL
//
//#define CONFIGURATION_BASE_ADDR 0x30UL
//#define CONFIGURATION_LENGTH 0x10UL
//#define CONFIGURATION_LAST_ADDR 0x3FUL

#define AUXILIARY_BASE_ADDR 0x40UL
#define AUXILIARY_LENGTH 0xB0UL
#define AUXILIARY_LAST_ADDR 0xEFUL

/*-----------------------------------------------------------------------------
* constants: absolute addresses of address Blocks
*---------------------------------------------------------------------------*/
#define EVENT_FUNC_RAW                           0x00
#define EVENT_ERR_RAW                            0x04
#define EVENT_SAFETY_RAW                         0x08
#define CONTROL_FUNC_CLR                         0x10
#define CONTROL_ERR_CLR                          0x14
#define CONTROL_SAFETY_CLR                       0x18
#define CONTROL_FUNC_ENA                         0x20
#define CONTROL_ERR_ENA                          0x24
#define CONTROL_SAFETY_ENA                       0x28
#define CONFIGURATION_CAPTURING_MODE             0x30
#define AUXILIARY_HDP                            0x40


/*-----------------------------------------------------------------------------
 * Register bit-field union types
 *---------------------------------------------------------------------------*/


/*-----------------------------------------------------------------------------
 * Register specific bit fields
 *---------------------------------------------------------------------------*/

//Register: FUNC_RAW Addr: 0x00
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Mhtxfq0irqU1 : 1;
    uint32_t Mhtxfq1irqU1 : 1;
    uint32_t Mhtxfq2irqU1 : 1;
    uint32_t Mhtxfq3irqU1 : 1;
    uint32_t Mhtxfq4irqU1 : 1;
    uint32_t Mhtxfq5irqU1 : 1;
    uint32_t Mhtxfq6irqU1 : 1;
    uint32_t Mhtxfq7irqU1 : 1;
    uint32_t Mhrxfq0irqU1 : 1;
    uint32_t Mhrxfq1irqU1 : 1;
    uint32_t Mhrxfq2irqU1 : 1;
    uint32_t Mhrxfq3irqU1 : 1;
    uint32_t Mhrxfq4irqU1 : 1;
    uint32_t Mhrxfq5irqU1 : 1;
    uint32_t Mhrxfq6irqU1 : 1;
    uint32_t Mhrxfq7irqU1 : 1;
    uint32_t MhtxpqirqU1 : 1;
    uint32_t MhstopirqU1 : 1;
    uint32_t MhrxfilterirqU1 : 1;
    uint32_t MhtxfilterirqU1 : 1;
    uint32_t MhtxabortirqU1 : 1;
    uint32_t MhrxabortirqU1 : 1;
    uint32_t MhstatsirqU1 : 1;
    uint32_t reserved23_u1 : 1;
    uint32_t PrteactiveU1 : 1;
    uint32_t PrtbusonU1 : 1;
    uint32_t PrttxevtU1 : 1;
    uint32_t PrtrxevtU1 : 1;
    uint32_t reserved28_u4 : 4;
  } as_s;
} EventFuncrawUt;

#define RESET_VAL_EVENT_FUNC_RAW 0x00000000


#define EVENT_FUNC_RAW_MH_TX_FQ0_IRQ_MASK 0x1
#define EVENT_FUNC_RAW_MH_TX_FQ0_IRQ_SHIFT 0

#define EVENT_FUNC_RAW_MH_TX_FQ1_IRQ_MASK 0x2
#define EVENT_FUNC_RAW_MH_TX_FQ1_IRQ_SHIFT 1

#define EVENT_FUNC_RAW_MH_TX_FQ2_IRQ_MASK 0x4
#define EVENT_FUNC_RAW_MH_TX_FQ2_IRQ_SHIFT 2

#define EVENT_FUNC_RAW_MH_TX_FQ3_IRQ_MASK 0x8
#define EVENT_FUNC_RAW_MH_TX_FQ3_IRQ_SHIFT 3

#define EVENT_FUNC_RAW_MH_TX_FQ4_IRQ_MASK 0x10
#define EVENT_FUNC_RAW_MH_TX_FQ4_IRQ_SHIFT 4

#define EVENT_FUNC_RAW_MH_TX_FQ5_IRQ_MASK 0x20
#define EVENT_FUNC_RAW_MH_TX_FQ5_IRQ_SHIFT 5

#define EVENT_FUNC_RAW_MH_TX_FQ6_IRQ_MASK 0x40
#define EVENT_FUNC_RAW_MH_TX_FQ6_IRQ_SHIFT 6

#define EVENT_FUNC_RAW_MH_TX_FQ7_IRQ_MASK 0x80
#define EVENT_FUNC_RAW_MH_TX_FQ7_IRQ_SHIFT 7

#define EVENT_FUNC_RAW_MH_RX_FQ0_IRQ_MASK 0x100
#define EVENT_FUNC_RAW_MH_RX_FQ0_IRQ_SHIFT 8

#define EVENT_FUNC_RAW_MH_RX_FQ1_IRQ_MASK 0x200
#define EVENT_FUNC_RAW_MH_RX_FQ1_IRQ_SHIFT 9

#define EVENT_FUNC_RAW_MH_RX_FQ2_IRQ_MASK 0x400
#define EVENT_FUNC_RAW_MH_RX_FQ2_IRQ_SHIFT 10

#define EVENT_FUNC_RAW_MH_RX_FQ3_IRQ_MASK 0x800
#define EVENT_FUNC_RAW_MH_RX_FQ3_IRQ_SHIFT 11

#define EVENT_FUNC_RAW_MH_RX_FQ4_IRQ_MASK 0x1000
#define EVENT_FUNC_RAW_MH_RX_FQ4_IRQ_SHIFT 12

#define EVENT_FUNC_RAW_MH_RX_FQ5_IRQ_MASK 0x2000
#define EVENT_FUNC_RAW_MH_RX_FQ5_IRQ_SHIFT 13

#define EVENT_FUNC_RAW_MH_RX_FQ6_IRQ_MASK 0x4000
#define EVENT_FUNC_RAW_MH_RX_FQ6_IRQ_SHIFT 14

#define EVENT_FUNC_RAW_MH_RX_FQ7_IRQ_MASK 0x8000
#define EVENT_FUNC_RAW_MH_RX_FQ7_IRQ_SHIFT 15

#define EVENT_FUNC_RAW_MH_TX_PQ_IRQ_MASK 0x10000
#define EVENT_FUNC_RAW_MH_TX_PQ_IRQ_SHIFT 16

#define EVENT_FUNC_RAW_MH_STOP_IRQ_MASK 0x20000
#define EVENT_FUNC_RAW_MH_STOP_IRQ_SHIFT 17

#define EVENT_FUNC_RAW_MH_RX_FILTER_IRQ_MASK 0x40000
#define EVENT_FUNC_RAW_MH_RX_FILTER_IRQ_SHIFT 18

#define EVENT_FUNC_RAW_MH_TX_FILTER_IRQ_MASK 0x80000
#define EVENT_FUNC_RAW_MH_TX_FILTER_IRQ_SHIFT 19

#define EVENT_FUNC_RAW_MH_TX_ABORT_IRQ_MASK 0x100000
#define EVENT_FUNC_RAW_MH_TX_ABORT_IRQ_SHIFT 20

#define EVENT_FUNC_RAW_MH_RX_ABORT_IRQ_MASK 0x200000
#define EVENT_FUNC_RAW_MH_RX_ABORT_IRQ_SHIFT 21

#define EVENT_FUNC_RAW_MH_STATS_IRQ_MASK 0x400000
#define EVENT_FUNC_RAW_MH_STATS_IRQ_SHIFT 22

#define EVENT_FUNC_RAW_PRT_E_ACTIVE_MASK 0x1000000
#define EVENT_FUNC_RAW_PRT_E_ACTIVE_SHIFT 24

#define EVENT_FUNC_RAW_PRT_BUS_ON_MASK 0x2000000
#define EVENT_FUNC_RAW_PRT_BUS_ON_SHIFT 25

#define EVENT_FUNC_RAW_PRT_TX_EVT_MASK 0x4000000
#define EVENT_FUNC_RAW_PRT_TX_EVT_SHIFT 26

#define EVENT_FUNC_RAW_PRT_RX_EVT_MASK 0x8000000
#define EVENT_FUNC_RAW_PRT_RX_EVT_SHIFT 27

//Register: ERR_RAW Addr: 0x04
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MhrxfiltererrU1 : 1;
    uint32_t MhmemsftyerrU1 : 1;
    uint32_t MhregcrcerrU1 : 1;
    uint32_t MhdescerrU1 : 1;
    uint32_t MhapparityerrU1 : 1;
    uint32_t MhdpparityerrU1 : 1;
    uint32_t MhdpseqerrU1 : 1;
    uint32_t MhdpdoerrU1 : 1;
    uint32_t MhdptoerrU1 : 1;
    uint32_t MhdmatoerrU1 : 1;
    uint32_t MhdmacherrU1 : 1;
    uint32_t MhrdresperrU1 : 1;
    uint32_t MhwrresperrU1 : 1;
    uint32_t MhmemtoerrU1 : 1;
    uint32_t reserved14_u2 : 2;
    uint32_t PrtabortedU1 : 1;
    uint32_t PrtusosU1 : 1;
    uint32_t PrttxduU1 : 1;
    uint32_t PrtrxdoU1 : 1;
    uint32_t PrtiffrqU1 : 1;
    uint32_t PrtbuserrU1 : 1;
    uint32_t PrtepassiveU1 : 1;
    uint32_t PrtbusoffU1 : 1;
    uint32_t reserved24_u4 : 4;
    uint32_t TopmuxtoerrU1 : 1;
    uint32_t reserved29_u3 : 3;
  } as_s;
} EventErrrawUt;

#define RESET_VAL_EVENT_ERR_RAW 0x00000000


#define EVENT_ERR_RAW_MH_RX_FILTER_ERR_MASK 0x1
#define EVENT_ERR_RAW_MH_RX_FILTER_ERR_SHIFT 0

#define EVENT_ERR_RAW_MH_MEM_SFTY_ERR_MASK 0x2
#define EVENT_ERR_RAW_MH_MEM_SFTY_ERR_SHIFT 1

#define EVENT_ERR_RAW_MH_REG_CRC_ERR_MASK 0x4
#define EVENT_ERR_RAW_MH_REG_CRC_ERR_SHIFT 2

#define EVENT_ERR_RAW_MH_DESC_ERR_MASK 0x8
#define EVENT_ERR_RAW_MH_DESC_ERR_SHIFT 3

#define EVENT_ERR_RAW_MH_AP_PARITY_ERR_MASK 0x10
#define EVENT_ERR_RAW_MH_AP_PARITY_ERR_SHIFT 4

#define EVENT_ERR_RAW_MH_DP_PARITY_ERR_MASK 0x20
#define EVENT_ERR_RAW_MH_DP_PARITY_ERR_SHIFT 5

#define EVENT_ERR_RAW_MH_DP_SEQ_ERR_MASK 0x40
#define EVENT_ERR_RAW_MH_DP_SEQ_ERR_SHIFT 6

#define EVENT_ERR_RAW_MH_DP_DO_ERR_MASK 0x80
#define EVENT_ERR_RAW_MH_DP_DO_ERR_SHIFT 7

#define EVENT_ERR_RAW_MH_DP_TO_ERR_MASK 0x100
#define EVENT_ERR_RAW_MH_DP_TO_ERR_SHIFT 8

#define EVENT_ERR_RAW_MH_DMA_TO_ERR_MASK 0x200
#define EVENT_ERR_RAW_MH_DMA_TO_ERR_SHIFT 9

#define EVENT_ERR_RAW_MH_DMA_CH_ERR_MASK 0x400
#define EVENT_ERR_RAW_MH_DMA_CH_ERR_SHIFT 10

#define EVENT_ERR_RAW_MH_RD_RESP_ERR_MASK 0x800
#define EVENT_ERR_RAW_MH_RD_RESP_ERR_SHIFT 11

#define EVENT_ERR_RAW_MH_WR_RESP_ERR_MASK 0x1000
#define EVENT_ERR_RAW_MH_WR_RESP_ERR_SHIFT 12

#define EVENT_ERR_RAW_MH_MEM_TO_ERR_MASK 0x2000
#define EVENT_ERR_RAW_MH_MEM_TO_ERR_SHIFT 13

#define EVENT_ERR_RAW_PRT_ABORTED_MASK 0x10000
#define EVENT_ERR_RAW_PRT_ABORTED_SHIFT 16

#define EVENT_ERR_RAW_PRT_USOS_MASK 0x20000
#define EVENT_ERR_RAW_PRT_USOS_SHIFT 17

#define EVENT_ERR_RAW_PRT_TX_DU_MASK 0x40000
#define EVENT_ERR_RAW_PRT_TX_DU_SHIFT 18

#define EVENT_ERR_RAW_PRT_RX_DO_MASK 0x80000
#define EVENT_ERR_RAW_PRT_RX_DO_SHIFT 19

#define EVENT_ERR_RAW_PRT_IFF_RQ_MASK 0x100000
#define EVENT_ERR_RAW_PRT_IFF_RQ_SHIFT 20

#define EVENT_ERR_RAW_PRT_BUS_ERR_MASK 0x200000
#define EVENT_ERR_RAW_PRT_BUS_ERR_SHIFT 21

#define EVENT_ERR_RAW_PRT_E_PASSIVE_MASK 0x400000
#define EVENT_ERR_RAW_PRT_E_PASSIVE_SHIFT 22

#define EVENT_ERR_RAW_PRT_BUS_OFF_MASK 0x800000
#define EVENT_ERR_RAW_PRT_BUS_OFF_SHIFT 23

#define EVENT_ERR_RAW_TOP_MUX_TO_ERR_MASK 0x10000000
#define EVENT_ERR_RAW_TOP_MUX_TO_ERR_SHIFT 28

//Register: SAFETY_RAW Addr: 0x08
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MhrxfiltererrU1 : 1;
    uint32_t MhmemsftyerrU1 : 1;
    uint32_t MhregcrcerrU1 : 1;
    uint32_t MhdescerrU1 : 1;
    uint32_t MhapparityerrU1 : 1;
    uint32_t MhdpparityerrU1 : 1;
    uint32_t MhdpseqerrU1 : 1;
    uint32_t MhdpdoerrU1 : 1;
    uint32_t MhdptoerrU1 : 1;
    uint32_t MhdmatoerrU1 : 1;
    uint32_t MhdmacherrU1 : 1;
    uint32_t MhrdresperrU1 : 1;
    uint32_t MhwrresperrU1 : 1;
    uint32_t MhmemtoerrU1 : 1;
    uint32_t reserved14_u2 : 2;
    uint32_t PrtabortedU1 : 1;
    uint32_t PrtusosU1 : 1;
    uint32_t PrttxduU1 : 1;
    uint32_t PrtrxdoU1 : 1;
    uint32_t PrtiffrqU1 : 1;
    uint32_t PrtbuserrU1 : 1;
    uint32_t PrtepassiveU1 : 1;
    uint32_t PrtbusoffU1 : 1;
    uint32_t reserved24_u4 : 4;
    uint32_t TopmuxtoerrU1 : 1;
    uint32_t reserved29_u3 : 3;
  } as_s;
} EventSafetyrawUt;

#define RESET_VAL_EVENT_SAFETY_RAW 0x00000000


#define EVENT_SAFETY_RAW_MH_RX_FILTER_ERR_MASK 0x1
#define EVENT_SAFETY_RAW_MH_RX_FILTER_ERR_SHIFT 0

#define EVENT_SAFETY_RAW_MH_MEM_SFTY_ERR_MASK 0x2
#define EVENT_SAFETY_RAW_MH_MEM_SFTY_ERR_SHIFT 1

#define EVENT_SAFETY_RAW_MH_REG_CRC_ERR_MASK 0x4
#define EVENT_SAFETY_RAW_MH_REG_CRC_ERR_SHIFT 2

#define EVENT_SAFETY_RAW_MH_DESC_ERR_MASK 0x8
#define EVENT_SAFETY_RAW_MH_DESC_ERR_SHIFT 3

#define EVENT_SAFETY_RAW_MH_AP_PARITY_ERR_MASK 0x10
#define EVENT_SAFETY_RAW_MH_AP_PARITY_ERR_SHIFT 4

#define EVENT_SAFETY_RAW_MH_DP_PARITY_ERR_MASK 0x20
#define EVENT_SAFETY_RAW_MH_DP_PARITY_ERR_SHIFT 5

#define EVENT_SAFETY_RAW_MH_DP_SEQ_ERR_MASK 0x40
#define EVENT_SAFETY_RAW_MH_DP_SEQ_ERR_SHIFT 6

#define EVENT_SAFETY_RAW_MH_DP_DO_ERR_MASK 0x80
#define EVENT_SAFETY_RAW_MH_DP_DO_ERR_SHIFT 7

#define EVENT_SAFETY_RAW_MH_DP_TO_ERR_MASK 0x100
#define EVENT_SAFETY_RAW_MH_DP_TO_ERR_SHIFT 8

#define EVENT_SAFETY_RAW_MH_DMA_TO_ERR_MASK 0x200
#define EVENT_SAFETY_RAW_MH_DMA_TO_ERR_SHIFT 9

#define EVENT_SAFETY_RAW_MH_DMA_CH_ERR_MASK 0x400
#define EVENT_SAFETY_RAW_MH_DMA_CH_ERR_SHIFT 10

#define EVENT_SAFETY_RAW_MH_RD_RESP_ERR_MASK 0x800
#define EVENT_SAFETY_RAW_MH_RD_RESP_ERR_SHIFT 11

#define EVENT_SAFETY_RAW_MH_WR_RESP_ERR_MASK 0x1000
#define EVENT_SAFETY_RAW_MH_WR_RESP_ERR_SHIFT 12

#define EVENT_SAFETY_RAW_MH_MEM_TO_ERR_MASK 0x2000
#define EVENT_SAFETY_RAW_MH_MEM_TO_ERR_SHIFT 13

#define EVENT_SAFETY_RAW_PRT_ABORTED_MASK 0x10000
#define EVENT_SAFETY_RAW_PRT_ABORTED_SHIFT 16

#define EVENT_SAFETY_RAW_PRT_USOS_MASK 0x20000
#define EVENT_SAFETY_RAW_PRT_USOS_SHIFT 17

#define EVENT_SAFETY_RAW_PRT_TX_DU_MASK 0x40000
#define EVENT_SAFETY_RAW_PRT_TX_DU_SHIFT 18

#define EVENT_SAFETY_RAW_PRT_RX_DO_MASK 0x80000
#define EVENT_SAFETY_RAW_PRT_RX_DO_SHIFT 19

#define EVENT_SAFETY_RAW_PRT_IFF_RQ_MASK 0x100000
#define EVENT_SAFETY_RAW_PRT_IFF_RQ_SHIFT 20

#define EVENT_SAFETY_RAW_PRT_BUS_ERR_MASK 0x200000
#define EVENT_SAFETY_RAW_PRT_BUS_ERR_SHIFT 21

#define EVENT_SAFETY_RAW_PRT_E_PASSIVE_MASK 0x400000
#define EVENT_SAFETY_RAW_PRT_E_PASSIVE_SHIFT 22

#define EVENT_SAFETY_RAW_PRT_BUS_OFF_MASK 0x800000
#define EVENT_SAFETY_RAW_PRT_BUS_OFF_SHIFT 23

#define EVENT_SAFETY_RAW_TOP_MUX_TO_ERR_MASK 0x10000000
#define EVENT_SAFETY_RAW_TOP_MUX_TO_ERR_SHIFT 28

//Register: FUNC_CLR Addr: 0x10
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Mhtxfq0irqU1 : 1;
    uint32_t Mhtxfq1irqU1 : 1;
    uint32_t Mhtxfq2irqU1 : 1;
    uint32_t Mhtxfq3irqU1 : 1;
    uint32_t Mhtxfq4irqU1 : 1;
    uint32_t Mhtxfq5irqU1 : 1;
    uint32_t Mhtxfq6irqU1 : 1;
    uint32_t Mhtxfq7irqU1 : 1;
    uint32_t Mhrxfq0irqU1 : 1;
    uint32_t Mhrxfq1irqU1 : 1;
    uint32_t Mhrxfq2irqU1 : 1;
    uint32_t Mhrxfq3irqU1 : 1;
    uint32_t Mhrxfq4irqU1 : 1;
    uint32_t Mhrxfq5irqU1 : 1;
    uint32_t Mhrxfq6irqU1 : 1;
    uint32_t Mhrxfq7irqU1 : 1;
    uint32_t MhtxpqirqU1 : 1;
    uint32_t MhstopirqU1 : 1;
    uint32_t MhrxfilterirqU1 : 1;
    uint32_t MhtxfilterirqU1 : 1;
    uint32_t MhtxabortirqU1 : 1;
    uint32_t MhrxabortirqU1 : 1;
    uint32_t MhstatsirqU1 : 1;
    uint32_t reserved23_u1 : 1;
    uint32_t PrteactiveU1 : 1;
    uint32_t PrtbusonU1 : 1;
    uint32_t PrttxevtU1 : 1;
    uint32_t PrtrxevtU1 : 1;
    uint32_t reserved28_u4 : 4;
  } as_s;
} ControlFuncclrUt;

#define RESET_VAL_CONTROL_FUNC_CLR 0x00000000


#define CONTROL_FUNC_CLR_MH_TX_FQ0_IRQ_MASK 0x1
#define CONTROL_FUNC_CLR_MH_TX_FQ0_IRQ_SHIFT 0

#define CONTROL_FUNC_CLR_MH_TX_FQ1_IRQ_MASK 0x2
#define CONTROL_FUNC_CLR_MH_TX_FQ1_IRQ_SHIFT 1

#define CONTROL_FUNC_CLR_MH_TX_FQ2_IRQ_MASK 0x4
#define CONTROL_FUNC_CLR_MH_TX_FQ2_IRQ_SHIFT 2

#define CONTROL_FUNC_CLR_MH_TX_FQ3_IRQ_MASK 0x8
#define CONTROL_FUNC_CLR_MH_TX_FQ3_IRQ_SHIFT 3

#define CONTROL_FUNC_CLR_MH_TX_FQ4_IRQ_MASK 0x10
#define CONTROL_FUNC_CLR_MH_TX_FQ4_IRQ_SHIFT 4

#define CONTROL_FUNC_CLR_MH_TX_FQ5_IRQ_MASK 0x20
#define CONTROL_FUNC_CLR_MH_TX_FQ5_IRQ_SHIFT 5

#define CONTROL_FUNC_CLR_MH_TX_FQ6_IRQ_MASK 0x40
#define CONTROL_FUNC_CLR_MH_TX_FQ6_IRQ_SHIFT 6

#define CONTROL_FUNC_CLR_MH_TX_FQ7_IRQ_MASK 0x80
#define CONTROL_FUNC_CLR_MH_TX_FQ7_IRQ_SHIFT 7

#define CONTROL_FUNC_CLR_MH_RX_FQ0_IRQ_MASK 0x100
#define CONTROL_FUNC_CLR_MH_RX_FQ0_IRQ_SHIFT 8

#define CONTROL_FUNC_CLR_MH_RX_FQ1_IRQ_MASK 0x200
#define CONTROL_FUNC_CLR_MH_RX_FQ1_IRQ_SHIFT 9

#define CONTROL_FUNC_CLR_MH_RX_FQ2_IRQ_MASK 0x400
#define CONTROL_FUNC_CLR_MH_RX_FQ2_IRQ_SHIFT 10

#define CONTROL_FUNC_CLR_MH_RX_FQ3_IRQ_MASK 0x800
#define CONTROL_FUNC_CLR_MH_RX_FQ3_IRQ_SHIFT 11

#define CONTROL_FUNC_CLR_MH_RX_FQ4_IRQ_MASK 0x1000
#define CONTROL_FUNC_CLR_MH_RX_FQ4_IRQ_SHIFT 12

#define CONTROL_FUNC_CLR_MH_RX_FQ5_IRQ_MASK 0x2000
#define CONTROL_FUNC_CLR_MH_RX_FQ5_IRQ_SHIFT 13

#define CONTROL_FUNC_CLR_MH_RX_FQ6_IRQ_MASK 0x4000
#define CONTROL_FUNC_CLR_MH_RX_FQ6_IRQ_SHIFT 14

#define CONTROL_FUNC_CLR_MH_RX_FQ7_IRQ_MASK 0x8000
#define CONTROL_FUNC_CLR_MH_RX_FQ7_IRQ_SHIFT 15

#define CONTROL_FUNC_CLR_MH_TX_PQ_IRQ_MASK 0x10000
#define CONTROL_FUNC_CLR_MH_TX_PQ_IRQ_SHIFT 16

#define CONTROL_FUNC_CLR_MH_STOP_IRQ_MASK 0x20000
#define CONTROL_FUNC_CLR_MH_STOP_IRQ_SHIFT 17

#define CONTROL_FUNC_CLR_MH_RX_FILTER_IRQ_MASK 0x40000
#define CONTROL_FUNC_CLR_MH_RX_FILTER_IRQ_SHIFT 18

#define CONTROL_FUNC_CLR_MH_TX_FILTER_IRQ_MASK 0x80000
#define CONTROL_FUNC_CLR_MH_TX_FILTER_IRQ_SHIFT 19

#define CONTROL_FUNC_CLR_MH_TX_ABORT_IRQ_MASK 0x100000
#define CONTROL_FUNC_CLR_MH_TX_ABORT_IRQ_SHIFT 20

#define CONTROL_FUNC_CLR_MH_RX_ABORT_IRQ_MASK 0x200000
#define CONTROL_FUNC_CLR_MH_RX_ABORT_IRQ_SHIFT 21

#define CONTROL_FUNC_CLR_MH_STATS_IRQ_MASK 0x400000
#define CONTROL_FUNC_CLR_MH_STATS_IRQ_SHIFT 22

#define CONTROL_FUNC_CLR_PRT_E_ACTIVE_MASK 0x1000000
#define CONTROL_FUNC_CLR_PRT_E_ACTIVE_SHIFT 24

#define CONTROL_FUNC_CLR_PRT_BUS_ON_MASK 0x2000000
#define CONTROL_FUNC_CLR_PRT_BUS_ON_SHIFT 25

#define CONTROL_FUNC_CLR_PRT_TX_EVT_MASK 0x4000000
#define CONTROL_FUNC_CLR_PRT_TX_EVT_SHIFT 26

#define CONTROL_FUNC_CLR_PRT_RX_EVT_MASK 0x8000000
#define CONTROL_FUNC_CLR_PRT_RX_EVT_SHIFT 27

//Register: ERR_CLR Addr: 0x14
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MhrxfiltererrU1 : 1;
    uint32_t MhmemsftyerrU1 : 1;
    uint32_t MhregcrcerrU1 : 1;
    uint32_t MhdescerrU1 : 1;
    uint32_t MhapparityerrU1 : 1;
    uint32_t MhdpparityerrU1 : 1;
    uint32_t MhdpseqerrU1 : 1;
    uint32_t MhdpdoerrU1 : 1;
    uint32_t MhdptoerrU1 : 1;
    uint32_t MhdmatoerrU1 : 1;
    uint32_t MhdmacherrU1 : 1;
    uint32_t MhrdresperrU1 : 1;
    uint32_t MhwrresperrU1 : 1;
    uint32_t MhmemtoerrU1 : 1;
    uint32_t reserved14_u2 : 2;
    uint32_t PrtabortedU1 : 1;
    uint32_t PrtusosU1 : 1;
    uint32_t PrttxduU1 : 1;
    uint32_t PrtrxdoU1 : 1;
    uint32_t PrtiffrqU1 : 1;
    uint32_t PrtbuserrU1 : 1;
    uint32_t PrtepassiveU1 : 1;
    uint32_t PrtbusoffU1 : 1;
    uint32_t reserved24_u4 : 4;
    uint32_t TopmuxtoerrU1 : 1;
    uint32_t reserved29_u3 : 3;
  } as_s;
} ControlErrclrUt;

#define RESET_VAL_CONTROL_ERR_CLR 0x00000000


#define CONTROL_ERR_CLR_MH_RX_FILTER_ERR_MASK 0x1
#define CONTROL_ERR_CLR_MH_RX_FILTER_ERR_SHIFT 0

#define CONTROL_ERR_CLR_MH_MEM_SFTY_ERR_MASK 0x2
#define CONTROL_ERR_CLR_MH_MEM_SFTY_ERR_SHIFT 1

#define CONTROL_ERR_CLR_MH_REG_CRC_ERR_MASK 0x4
#define CONTROL_ERR_CLR_MH_REG_CRC_ERR_SHIFT 2

#define CONTROL_ERR_CLR_MH_DESC_ERR_MASK 0x8
#define CONTROL_ERR_CLR_MH_DESC_ERR_SHIFT 3

#define CONTROL_ERR_CLR_MH_AP_PARITY_ERR_MASK 0x10
#define CONTROL_ERR_CLR_MH_AP_PARITY_ERR_SHIFT 4

#define CONTROL_ERR_CLR_MH_DP_PARITY_ERR_MASK 0x20
#define CONTROL_ERR_CLR_MH_DP_PARITY_ERR_SHIFT 5

#define CONTROL_ERR_CLR_MH_DP_SEQ_ERR_MASK 0x40
#define CONTROL_ERR_CLR_MH_DP_SEQ_ERR_SHIFT 6

#define CONTROL_ERR_CLR_MH_DP_DO_ERR_MASK 0x80
#define CONTROL_ERR_CLR_MH_DP_DO_ERR_SHIFT 7

#define CONTROL_ERR_CLR_MH_DP_TO_ERR_MASK 0x100
#define CONTROL_ERR_CLR_MH_DP_TO_ERR_SHIFT 8

#define CONTROL_ERR_CLR_MH_DMA_TO_ERR_MASK 0x200
#define CONTROL_ERR_CLR_MH_DMA_TO_ERR_SHIFT 9

#define CONTROL_ERR_CLR_MH_DMA_CH_ERR_MASK 0x400
#define CONTROL_ERR_CLR_MH_DMA_CH_ERR_SHIFT 10

#define CONTROL_ERR_CLR_MH_RD_RESP_ERR_MASK 0x800
#define CONTROL_ERR_CLR_MH_RD_RESP_ERR_SHIFT 11

#define CONTROL_ERR_CLR_MH_WR_RESP_ERR_MASK 0x1000
#define CONTROL_ERR_CLR_MH_WR_RESP_ERR_SHIFT 12

#define CONTROL_ERR_CLR_MH_MEM_TO_ERR_MASK 0x2000
#define CONTROL_ERR_CLR_MH_MEM_TO_ERR_SHIFT 13

#define CONTROL_ERR_CLR_PRT_ABORTED_MASK 0x10000
#define CONTROL_ERR_CLR_PRT_ABORTED_SHIFT 16

#define CONTROL_ERR_CLR_PRT_USOS_MASK 0x20000
#define CONTROL_ERR_CLR_PRT_USOS_SHIFT 17

#define CONTROL_ERR_CLR_PRT_TX_DU_MASK 0x40000
#define CONTROL_ERR_CLR_PRT_TX_DU_SHIFT 18

#define CONTROL_ERR_CLR_PRT_RX_DO_MASK 0x80000
#define CONTROL_ERR_CLR_PRT_RX_DO_SHIFT 19

#define CONTROL_ERR_CLR_PRT_IFF_RQ_MASK 0x100000
#define CONTROL_ERR_CLR_PRT_IFF_RQ_SHIFT 20

#define CONTROL_ERR_CLR_PRT_BUS_ERR_MASK 0x200000
#define CONTROL_ERR_CLR_PRT_BUS_ERR_SHIFT 21

#define CONTROL_ERR_CLR_PRT_E_PASSIVE_MASK 0x400000
#define CONTROL_ERR_CLR_PRT_E_PASSIVE_SHIFT 22

#define CONTROL_ERR_CLR_PRT_BUS_OFF_MASK 0x800000
#define CONTROL_ERR_CLR_PRT_BUS_OFF_SHIFT 23

#define CONTROL_ERR_CLR_TOP_MUX_TO_ERR_MASK 0x10000000
#define CONTROL_ERR_CLR_TOP_MUX_TO_ERR_SHIFT 28

//Register: SAFETY_CLR Addr: 0x18
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MhrxfiltererrU1 : 1;
    uint32_t MhmemsftyerrU1 : 1;
    uint32_t MhregcrcerrU1 : 1;
    uint32_t MhdescerrU1 : 1;
    uint32_t MhapparityerrU1 : 1;
    uint32_t MhdpparityerrU1 : 1;
    uint32_t MhdpseqerrU1 : 1;
    uint32_t MhdpdoerrU1 : 1;
    uint32_t MhdptoerrU1 : 1;
    uint32_t MhdmatoerrU1 : 1;
    uint32_t MhdmacherrU1 : 1;
    uint32_t MhrdresperrU1 : 1;
    uint32_t MhwrresperrU1 : 1;
    uint32_t MhmemtoerrU1 : 1;
    uint32_t reserved14_u2 : 2;
    uint32_t PrtabortedU1 : 1;
    uint32_t PrtusosU1 : 1;
    uint32_t PrttxduU1 : 1;
    uint32_t PrtrxdoU1 : 1;
    uint32_t PrtiffrqU1 : 1;
    uint32_t PrtbuserrU1 : 1;
    uint32_t PrtepassiveU1 : 1;
    uint32_t PrtbusoffU1 : 1;
    uint32_t reserved24_u4 : 4;
    uint32_t TopmuxtoerrU1 : 1;
    uint32_t reserved29_u3 : 3;
  } as_s;
} ControlSafetyclrUt;

#define RESET_VAL_CONTROL_SAFETY_CLR 0x00000000


#define CONTROL_SAFETY_CLR_MH_RX_FILTER_ERR_MASK 0x1
#define CONTROL_SAFETY_CLR_MH_RX_FILTER_ERR_SHIFT 0

#define CONTROL_SAFETY_CLR_MH_MEM_SFTY_ERR_MASK 0x2
#define CONTROL_SAFETY_CLR_MH_MEM_SFTY_ERR_SHIFT 1

#define CONTROL_SAFETY_CLR_MH_REG_CRC_ERR_MASK 0x4
#define CONTROL_SAFETY_CLR_MH_REG_CRC_ERR_SHIFT 2

#define CONTROL_SAFETY_CLR_MH_DESC_ERR_MASK 0x8
#define CONTROL_SAFETY_CLR_MH_DESC_ERR_SHIFT 3

#define CONTROL_SAFETY_CLR_MH_AP_PARITY_ERR_MASK 0x10
#define CONTROL_SAFETY_CLR_MH_AP_PARITY_ERR_SHIFT 4

#define CONTROL_SAFETY_CLR_MH_DP_PARITY_ERR_MASK 0x20
#define CONTROL_SAFETY_CLR_MH_DP_PARITY_ERR_SHIFT 5

#define CONTROL_SAFETY_CLR_MH_DP_SEQ_ERR_MASK 0x40
#define CONTROL_SAFETY_CLR_MH_DP_SEQ_ERR_SHIFT 6

#define CONTROL_SAFETY_CLR_MH_DP_DO_ERR_MASK 0x80
#define CONTROL_SAFETY_CLR_MH_DP_DO_ERR_SHIFT 7

#define CONTROL_SAFETY_CLR_MH_DP_TO_ERR_MASK 0x100
#define CONTROL_SAFETY_CLR_MH_DP_TO_ERR_SHIFT 8

#define CONTROL_SAFETY_CLR_MH_DMA_TO_ERR_MASK 0x200
#define CONTROL_SAFETY_CLR_MH_DMA_TO_ERR_SHIFT 9

#define CONTROL_SAFETY_CLR_MH_DMA_CH_ERR_MASK 0x400
#define CONTROL_SAFETY_CLR_MH_DMA_CH_ERR_SHIFT 10

#define CONTROL_SAFETY_CLR_MH_RD_RESP_ERR_MASK 0x800
#define CONTROL_SAFETY_CLR_MH_RD_RESP_ERR_SHIFT 11

#define CONTROL_SAFETY_CLR_MH_WR_RESP_ERR_MASK 0x1000
#define CONTROL_SAFETY_CLR_MH_WR_RESP_ERR_SHIFT 12

#define CONTROL_SAFETY_CLR_MH_MEM_TO_ERR_MASK 0x2000
#define CONTROL_SAFETY_CLR_MH_MEM_TO_ERR_SHIFT 13

#define CONTROL_SAFETY_CLR_PRT_ABORTED_MASK 0x10000
#define CONTROL_SAFETY_CLR_PRT_ABORTED_SHIFT 16

#define CONTROL_SAFETY_CLR_PRT_USOS_MASK 0x20000
#define CONTROL_SAFETY_CLR_PRT_USOS_SHIFT 17

#define CONTROL_SAFETY_CLR_PRT_TX_DU_MASK 0x40000
#define CONTROL_SAFETY_CLR_PRT_TX_DU_SHIFT 18

#define CONTROL_SAFETY_CLR_PRT_RX_DO_MASK 0x80000
#define CONTROL_SAFETY_CLR_PRT_RX_DO_SHIFT 19

#define CONTROL_SAFETY_CLR_PRT_IFF_RQ_MASK 0x100000
#define CONTROL_SAFETY_CLR_PRT_IFF_RQ_SHIFT 20

#define CONTROL_SAFETY_CLR_PRT_BUS_ERR_MASK 0x200000
#define CONTROL_SAFETY_CLR_PRT_BUS_ERR_SHIFT 21

#define CONTROL_SAFETY_CLR_PRT_E_PASSIVE_MASK 0x400000
#define CONTROL_SAFETY_CLR_PRT_E_PASSIVE_SHIFT 22

#define CONTROL_SAFETY_CLR_PRT_BUS_OFF_MASK 0x800000
#define CONTROL_SAFETY_CLR_PRT_BUS_OFF_SHIFT 23

#define CONTROL_SAFETY_CLR_TOP_MUX_TO_ERR_MASK 0x10000000
#define CONTROL_SAFETY_CLR_TOP_MUX_TO_ERR_SHIFT 28

//Register: FUNC_ENA Addr: 0x20
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t Mhtxfq0irqU1 : 1;
    uint32_t Mhtxfq1irqU1 : 1;
    uint32_t Mhtxfq2irqU1 : 1;
    uint32_t Mhtxfq3irqU1 : 1;
    uint32_t Mhtxfq4irqU1 : 1;
    uint32_t Mhtxfq5irqU1 : 1;
    uint32_t Mhtxfq6irqU1 : 1;
    uint32_t Mhtxfq7irqU1 : 1;
    uint32_t Mhrxfq0irqU1 : 1;
    uint32_t Mhrxfq1irqU1 : 1;
    uint32_t Mhrxfq2irqU1 : 1;
    uint32_t Mhrxfq3irqU1 : 1;
    uint32_t Mhrxfq4irqU1 : 1;
    uint32_t Mhrxfq5irqU1 : 1;
    uint32_t Mhrxfq6irqU1 : 1;
    uint32_t Mhrxfq7irqU1 : 1;
    uint32_t MhtxpqirqU1 : 1;
    uint32_t MhstopirqU1 : 1;
    uint32_t MhrxfilterirqU1 : 1;
    uint32_t MhtxfilterirqU1 : 1;
    uint32_t MhtxabortirqU1 : 1;
    uint32_t MhrxabortirqU1 : 1;
    uint32_t MhstatsirqU1 : 1;
    uint32_t reserved23_u1 : 1;
    uint32_t PrteactiveU1 : 1;
    uint32_t PrtbusonU1 : 1;
    uint32_t PrttxevtU1 : 1;
    uint32_t PrtrxevtU1 : 1;
    uint32_t reserved28_u4 : 4;
  } as_s;
} ControlFuncenaUt;

#define RESET_VAL_CONTROL_FUNC_ENA 0x00000000


#define CONTROL_FUNC_ENA_MH_TX_FQ0_IRQ_MASK 0x1
#define CONTROL_FUNC_ENA_MH_TX_FQ0_IRQ_SHIFT 0

#define CONTROL_FUNC_ENA_MH_TX_FQ1_IRQ_MASK 0x2
#define CONTROL_FUNC_ENA_MH_TX_FQ1_IRQ_SHIFT 1

#define CONTROL_FUNC_ENA_MH_TX_FQ2_IRQ_MASK 0x4
#define CONTROL_FUNC_ENA_MH_TX_FQ2_IRQ_SHIFT 2

#define CONTROL_FUNC_ENA_MH_TX_FQ3_IRQ_MASK 0x8
#define CONTROL_FUNC_ENA_MH_TX_FQ3_IRQ_SHIFT 3

#define CONTROL_FUNC_ENA_MH_TX_FQ4_IRQ_MASK 0x10
#define CONTROL_FUNC_ENA_MH_TX_FQ4_IRQ_SHIFT 4

#define CONTROL_FUNC_ENA_MH_TX_FQ5_IRQ_MASK 0x20
#define CONTROL_FUNC_ENA_MH_TX_FQ5_IRQ_SHIFT 5

#define CONTROL_FUNC_ENA_MH_TX_FQ6_IRQ_MASK 0x40
#define CONTROL_FUNC_ENA_MH_TX_FQ6_IRQ_SHIFT 6

#define CONTROL_FUNC_ENA_MH_TX_FQ7_IRQ_MASK 0x80
#define CONTROL_FUNC_ENA_MH_TX_FQ7_IRQ_SHIFT 7

#define CONTROL_FUNC_ENA_MH_RX_FQ0_IRQ_MASK 0x100
#define CONTROL_FUNC_ENA_MH_RX_FQ0_IRQ_SHIFT 8

#define CONTROL_FUNC_ENA_MH_RX_FQ1_IRQ_MASK 0x200
#define CONTROL_FUNC_ENA_MH_RX_FQ1_IRQ_SHIFT 9

#define CONTROL_FUNC_ENA_MH_RX_FQ2_IRQ_MASK 0x400
#define CONTROL_FUNC_ENA_MH_RX_FQ2_IRQ_SHIFT 10

#define CONTROL_FUNC_ENA_MH_RX_FQ3_IRQ_MASK 0x800
#define CONTROL_FUNC_ENA_MH_RX_FQ3_IRQ_SHIFT 11

#define CONTROL_FUNC_ENA_MH_RX_FQ4_IRQ_MASK 0x1000
#define CONTROL_FUNC_ENA_MH_RX_FQ4_IRQ_SHIFT 12

#define CONTROL_FUNC_ENA_MH_RX_FQ5_IRQ_MASK 0x2000
#define CONTROL_FUNC_ENA_MH_RX_FQ5_IRQ_SHIFT 13

#define CONTROL_FUNC_ENA_MH_RX_FQ6_IRQ_MASK 0x4000
#define CONTROL_FUNC_ENA_MH_RX_FQ6_IRQ_SHIFT 14

#define CONTROL_FUNC_ENA_MH_RX_FQ7_IRQ_MASK 0x8000
#define CONTROL_FUNC_ENA_MH_RX_FQ7_IRQ_SHIFT 15

#define CONTROL_FUNC_ENA_MH_TX_PQ_IRQ_MASK 0x10000
#define CONTROL_FUNC_ENA_MH_TX_PQ_IRQ_SHIFT 16

#define CONTROL_FUNC_ENA_MH_STOP_IRQ_MASK 0x20000
#define CONTROL_FUNC_ENA_MH_STOP_IRQ_SHIFT 17

#define CONTROL_FUNC_ENA_MH_RX_FILTER_IRQ_MASK 0x40000
#define CONTROL_FUNC_ENA_MH_RX_FILTER_IRQ_SHIFT 18

#define CONTROL_FUNC_ENA_MH_TX_FILTER_IRQ_MASK 0x80000
#define CONTROL_FUNC_ENA_MH_TX_FILTER_IRQ_SHIFT 19

#define CONTROL_FUNC_ENA_MH_TX_ABORT_IRQ_MASK 0x100000
#define CONTROL_FUNC_ENA_MH_TX_ABORT_IRQ_SHIFT 20

#define CONTROL_FUNC_ENA_MH_RX_ABORT_IRQ_MASK 0x200000
#define CONTROL_FUNC_ENA_MH_RX_ABORT_IRQ_SHIFT 21

#define CONTROL_FUNC_ENA_MH_STATS_IRQ_MASK 0x400000
#define CONTROL_FUNC_ENA_MH_STATS_IRQ_SHIFT 22

#define CONTROL_FUNC_ENA_PRT_E_ACTIVE_MASK 0x1000000
#define CONTROL_FUNC_ENA_PRT_E_ACTIVE_SHIFT 24

#define CONTROL_FUNC_ENA_PRT_BUS_ON_MASK 0x2000000
#define CONTROL_FUNC_ENA_PRT_BUS_ON_SHIFT 25

#define CONTROL_FUNC_ENA_PRT_TX_EVT_MASK 0x4000000
#define CONTROL_FUNC_ENA_PRT_TX_EVT_SHIFT 26

#define CONTROL_FUNC_ENA_PRT_RX_EVT_MASK 0x8000000
#define CONTROL_FUNC_ENA_PRT_RX_EVT_SHIFT 27

//Register: ERR_ENA Addr: 0x24
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MhrxfiltererrU1 : 1;
    uint32_t MhmemsftyerrU1 : 1;
    uint32_t MhregcrcerrU1 : 1;
    uint32_t MhdescerrU1 : 1;
    uint32_t MhapparityerrU1 : 1;
    uint32_t MhdpparityerrU1 : 1;
    uint32_t MhdpseqerrU1 : 1;
    uint32_t MhdpdoerrU1 : 1;
    uint32_t MhdptoerrU1 : 1;
    uint32_t MhdmatoerrU1 : 1;
    uint32_t MhdmacherrU1 : 1;
    uint32_t MhrdresperrU1 : 1;
    uint32_t MhwrresperrU1 : 1;
    uint32_t MhmemtoerrU1 : 1;
    uint32_t reserved14_u2 : 2;
    uint32_t PrtabortedU1 : 1;
    uint32_t PrtusosU1 : 1;
    uint32_t PrttxduU1 : 1;
    uint32_t PrtrxdoU1 : 1;
    uint32_t PrtiffrqU1 : 1;
    uint32_t PrtbuserrU1 : 1;
    uint32_t PrtepassiveU1 : 1;
    uint32_t PrtbusoffU1 : 1;
    uint32_t reserved24_u4 : 4;
    uint32_t TopmuxtoerrU1 : 1;
    uint32_t reserved29_u3 : 3;
  } as_s;
} ControlErrenaUt;

#define RESET_VAL_CONTROL_ERR_ENA 0x00000000


#define CONTROL_ERR_ENA_MH_RX_FILTER_ERR_MASK 0x1
#define CONTROL_ERR_ENA_MH_RX_FILTER_ERR_SHIFT 0

#define CONTROL_ERR_ENA_MH_MEM_SFTY_ERR_MASK 0x2
#define CONTROL_ERR_ENA_MH_MEM_SFTY_ERR_SHIFT 1

#define CONTROL_ERR_ENA_MH_REG_CRC_ERR_MASK 0x4
#define CONTROL_ERR_ENA_MH_REG_CRC_ERR_SHIFT 2

#define CONTROL_ERR_ENA_MH_DESC_ERR_MASK 0x8
#define CONTROL_ERR_ENA_MH_DESC_ERR_SHIFT 3

#define CONTROL_ERR_ENA_MH_AP_PARITY_ERR_MASK 0x10
#define CONTROL_ERR_ENA_MH_AP_PARITY_ERR_SHIFT 4

#define CONTROL_ERR_ENA_MH_DP_PARITY_ERR_MASK 0x20
#define CONTROL_ERR_ENA_MH_DP_PARITY_ERR_SHIFT 5

#define CONTROL_ERR_ENA_MH_DP_SEQ_ERR_MASK 0x40
#define CONTROL_ERR_ENA_MH_DP_SEQ_ERR_SHIFT 6

#define CONTROL_ERR_ENA_MH_DP_DO_ERR_MASK 0x80
#define CONTROL_ERR_ENA_MH_DP_DO_ERR_SHIFT 7

#define CONTROL_ERR_ENA_MH_DP_TO_ERR_MASK 0x100
#define CONTROL_ERR_ENA_MH_DP_TO_ERR_SHIFT 8

#define CONTROL_ERR_ENA_MH_DMA_TO_ERR_MASK 0x200
#define CONTROL_ERR_ENA_MH_DMA_TO_ERR_SHIFT 9

#define CONTROL_ERR_ENA_MH_DMA_CH_ERR_MASK 0x400
#define CONTROL_ERR_ENA_MH_DMA_CH_ERR_SHIFT 10

#define CONTROL_ERR_ENA_MH_RD_RESP_ERR_MASK 0x800
#define CONTROL_ERR_ENA_MH_RD_RESP_ERR_SHIFT 11

#define CONTROL_ERR_ENA_MH_WR_RESP_ERR_MASK 0x1000
#define CONTROL_ERR_ENA_MH_WR_RESP_ERR_SHIFT 12

#define CONTROL_ERR_ENA_MH_MEM_TO_ERR_MASK 0x2000
#define CONTROL_ERR_ENA_MH_MEM_TO_ERR_SHIFT 13

#define CONTROL_ERR_ENA_PRT_ABORTED_MASK 0x10000
#define CONTROL_ERR_ENA_PRT_ABORTED_SHIFT 16

#define CONTROL_ERR_ENA_PRT_USOS_MASK 0x20000
#define CONTROL_ERR_ENA_PRT_USOS_SHIFT 17

#define CONTROL_ERR_ENA_PRT_TX_DU_MASK 0x40000
#define CONTROL_ERR_ENA_PRT_TX_DU_SHIFT 18

#define CONTROL_ERR_ENA_PRT_RX_DO_MASK 0x80000
#define CONTROL_ERR_ENA_PRT_RX_DO_SHIFT 19

#define CONTROL_ERR_ENA_PRT_IFF_RQ_MASK 0x100000
#define CONTROL_ERR_ENA_PRT_IFF_RQ_SHIFT 20

#define CONTROL_ERR_ENA_PRT_BUS_ERR_MASK 0x200000
#define CONTROL_ERR_ENA_PRT_BUS_ERR_SHIFT 21

#define CONTROL_ERR_ENA_PRT_E_PASSIVE_MASK 0x400000
#define CONTROL_ERR_ENA_PRT_E_PASSIVE_SHIFT 22

#define CONTROL_ERR_ENA_PRT_BUS_OFF_MASK 0x800000
#define CONTROL_ERR_ENA_PRT_BUS_OFF_SHIFT 23

#define CONTROL_ERR_ENA_TOP_MUX_TO_ERR_MASK 0x10000000
#define CONTROL_ERR_ENA_TOP_MUX_TO_ERR_SHIFT 28

//Register: SAFETY_ENA Addr: 0x28
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t MhrxfiltererrU1 : 1;
    uint32_t MhmemsftyerrU1 : 1;
    uint32_t MhregcrcerrU1 : 1;
    uint32_t MhdescerrU1 : 1;
    uint32_t MhapparityerrU1 : 1;
    uint32_t MhdpparityerrU1 : 1;
    uint32_t MhdpseqerrU1 : 1;
    uint32_t MhdpdoerrU1 : 1;
    uint32_t MhdptoerrU1 : 1;
    uint32_t MhdmatoerrU1 : 1;
    uint32_t MhdmacherrU1 : 1;
    uint32_t MhrdresperrU1 : 1;
    uint32_t MhwrresperrU1 : 1;
    uint32_t MhmemtoerrU1 : 1;
    uint32_t reserved14_u2 : 2;
    uint32_t PrtabortedU1 : 1;
    uint32_t PrtusosU1 : 1;
    uint32_t PrttxduU1 : 1;
    uint32_t PrtrxdoU1 : 1;
    uint32_t PrtiffrqU1 : 1;
    uint32_t PrtbuserrU1 : 1;
    uint32_t PrtepassiveU1 : 1;
    uint32_t PrtbusoffU1 : 1;
    uint32_t reserved24_u4 : 4;
    uint32_t TopmuxtoerrU1 : 1;
    uint32_t reserved29_u3 : 3;
  } as_s;
} ControlSafetyenaUt;

#define RESET_VAL_CONTROL_SAFETY_ENA 0x00000000


#define CONTROL_SAFETY_ENA_MH_RX_FILTER_ERR_MASK 0x1
#define CONTROL_SAFETY_ENA_MH_RX_FILTER_ERR_SHIFT 0

#define CONTROL_SAFETY_ENA_MH_MEM_SFTY_ERR_MASK 0x2
#define CONTROL_SAFETY_ENA_MH_MEM_SFTY_ERR_SHIFT 1

#define CONTROL_SAFETY_ENA_MH_REG_CRC_ERR_MASK 0x4
#define CONTROL_SAFETY_ENA_MH_REG_CRC_ERR_SHIFT 2

#define CONTROL_SAFETY_ENA_MH_DESC_ERR_MASK 0x8
#define CONTROL_SAFETY_ENA_MH_DESC_ERR_SHIFT 3

#define CONTROL_SAFETY_ENA_MH_AP_PARITY_ERR_MASK 0x10
#define CONTROL_SAFETY_ENA_MH_AP_PARITY_ERR_SHIFT 4

#define CONTROL_SAFETY_ENA_MH_DP_PARITY_ERR_MASK 0x20
#define CONTROL_SAFETY_ENA_MH_DP_PARITY_ERR_SHIFT 5

#define CONTROL_SAFETY_ENA_MH_DP_SEQ_ERR_MASK 0x40
#define CONTROL_SAFETY_ENA_MH_DP_SEQ_ERR_SHIFT 6

#define CONTROL_SAFETY_ENA_MH_DP_DO_ERR_MASK 0x80
#define CONTROL_SAFETY_ENA_MH_DP_DO_ERR_SHIFT 7

#define CONTROL_SAFETY_ENA_MH_DP_TO_ERR_MASK 0x100
#define CONTROL_SAFETY_ENA_MH_DP_TO_ERR_SHIFT 8

#define CONTROL_SAFETY_ENA_MH_DMA_TO_ERR_MASK 0x200
#define CONTROL_SAFETY_ENA_MH_DMA_TO_ERR_SHIFT 9

#define CONTROL_SAFETY_ENA_MH_DMA_CH_ERR_MASK 0x400
#define CONTROL_SAFETY_ENA_MH_DMA_CH_ERR_SHIFT 10

#define CONTROL_SAFETY_ENA_MH_RD_RESP_ERR_MASK 0x800
#define CONTROL_SAFETY_ENA_MH_RD_RESP_ERR_SHIFT 11

#define CONTROL_SAFETY_ENA_MH_WR_RESP_ERR_MASK 0x1000
#define CONTROL_SAFETY_ENA_MH_WR_RESP_ERR_SHIFT 12

#define CONTROL_SAFETY_ENA_MH_MEM_TO_ERR_MASK 0x2000
#define CONTROL_SAFETY_ENA_MH_MEM_TO_ERR_SHIFT 13

#define CONTROL_SAFETY_ENA_PRT_ABORTED_MASK 0x10000
#define CONTROL_SAFETY_ENA_PRT_ABORTED_SHIFT 16

#define CONTROL_SAFETY_ENA_PRT_USOS_MASK 0x20000
#define CONTROL_SAFETY_ENA_PRT_USOS_SHIFT 17

#define CONTROL_SAFETY_ENA_PRT_TX_DU_MASK 0x40000
#define CONTROL_SAFETY_ENA_PRT_TX_DU_SHIFT 18

#define CONTROL_SAFETY_ENA_PRT_RX_DO_MASK 0x80000
#define CONTROL_SAFETY_ENA_PRT_RX_DO_SHIFT 19

#define CONTROL_SAFETY_ENA_PRT_IFF_RQ_MASK 0x100000
#define CONTROL_SAFETY_ENA_PRT_IFF_RQ_SHIFT 20

#define CONTROL_SAFETY_ENA_PRT_BUS_ERR_MASK 0x200000
#define CONTROL_SAFETY_ENA_PRT_BUS_ERR_SHIFT 21

#define CONTROL_SAFETY_ENA_PRT_E_PASSIVE_MASK 0x400000
#define CONTROL_SAFETY_ENA_PRT_E_PASSIVE_SHIFT 22

#define CONTROL_SAFETY_ENA_PRT_BUS_OFF_MASK 0x800000
#define CONTROL_SAFETY_ENA_PRT_BUS_OFF_SHIFT 23

#define CONTROL_SAFETY_ENA_TOP_MUX_TO_ERR_MASK 0x10000000
#define CONTROL_SAFETY_ENA_TOP_MUX_TO_ERR_SHIFT 28

//Register: CAPTURING_MODE Addr: 0x30
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t FuncU1 : 1;
    uint32_t ErrU1 : 1;
    uint32_t SafetyU1 : 1;
    uint32_t reserved3_u29 : 29;
  } as_s;
} ConfigurationCapturingmodeUt;

#define RESET_VAL_CONFIGURATION_CAPTURING_MODE 0x00000007


#define CONFIGURATION_CAPTURING_MODE_FUNC_MASK 0x1
#define CONFIGURATION_CAPTURING_MODE_FUNC_SHIFT 0

#define CONFIGURATION_CAPTURING_MODE_ERR_MASK 0x2
#define CONFIGURATION_CAPTURING_MODE_ERR_SHIFT 1

#define CONFIGURATION_CAPTURING_MODE_SAFETY_MASK 0x4
#define CONFIGURATION_CAPTURING_MODE_SAFETY_SHIFT 2

//Register: HDP Addr: 0x40
typedef volatile union
{
  uint32_t as_uint32;
  struct
  {
    uint32_t HdpselU1 : 1;
    uint32_t reserved1_u31 : 31;
  } as_s;
} AuxiliaryHdpUt;

#define RESET_VAL_AUXILIARY_HDP 0x00000000


#define AUXILIARY_HDP_HDP_SEL_MASK 0x1
#define AUXILIARY_HDP_HDP_SEL_SHIFT 0

#endif /* XCAN_IRC_REGDEF_H */
